const ipaData = {
    vowels: {
        monophthongs: [
            { id: "i-long", phonetic: "i:", type: "Long Vowel", examples: ["see|/si:/|(v)|nhìn, thấy", "me|/mi:/|(pro)|tôi", "tree|/tri:/|(n)|cái cây", "free|/fri:/|(adj)|tự do, miễn phí", "three|/θri:/|(n)|số ba", "green|/gri:n/|(adj)|màu xanh lá", "meet|/mi:t/|(v)|gặp gỡ", "need|/ni:d/|(v)|cần", "keep|/ki:p/|(v)|giữ", "sleep|/sli:p/|(v)|ngủ", "feel|/fi:l/|(v)|cảm thấy", "week|/wi:k/|(n)|tuần", "read|/ri:d/|(v)|đọc", "eat|/i:t/|(v)|ăn", "meat|/mi:t/|(n)|thịt"] },
            { id: "i-short", phonetic: "ɪ", type: "Short Vowel", examples: ["it|/ɪt/|(pro)|nó", "is|/ɪz/|(v)|là", "in|/ɪn/|(prep)|trong", "if|/ɪf/|(conj)|nếu", "his|/hɪz/|(pro)|của anh ấy", "him|/hɪm/|(pro)|anh ấy", "big|/bɪg/|(adj)|to lớn", "pig|/pɪg/|(n)|con lợn", "dig|/dɪg/|(v)|đào", "sit|/sɪt/|(v)|ngồi", "hit|/hɪt/|(v)|đánh", "fit|/fɪt/|(adj)|vừa vặn", "bit|/bɪt/|(n)|một chút", "with|/wɪð/|(prep)|với", "this|/ðɪs/|(pro)|cái này"] },
            { id: "u-short", phonetic: "ʊ", type: "Short Vowel", examples: ["put|/pʊt/|(v)|đặt, để", "push|/pʊʃ/|(v)|đẩy", "pull|/pʊl/|(v)|kéo", "full|/fʊl/|(adj)|đầy", "bull|/bʊl/|(n)|bò tót", "good|/gʊd/|(adj)|tốt", "wood|/wʊd/|(n)|gỗ", "stood|/stʊd/|(v)|đã đứng (quá khứ của stand)", "foot|/fʊt/|(n)|bàn chân", "book|/bʊk/|(n)|quyển sách", "look|/lʊk/|(v)|nhìn", "took|/tʊk/|(v)|đã lấy (quá khứ của take)", "cook|/kʊk/|(v)|nấu ăn", "hook|/hʊk/|(n)|cái móc", "shook|/ʃʊk/|(v)|đã lắc (quá khứ của shake)"] },
            { id: "u-long", phonetic: "u:", type: "Long Vowel", examples: ["too|/tu:/|(adv)|quá, cũng", "zoo|/zu:/|(n)|sở thú", "food|/fu:d/|(n)|thức ăn", "moon|/mu:n/|(n)|mặt trăng", "soon|/su:n/|(adv)|sớm", "room|/ru:m/|(n)|phòng", "boot|/bu:t/|(n)|ủng", "root|/ru:t/|(n)|rễ cây", "shoot|/ʃu:t/|(v)|bắn", "pool|/pu:l/|(n)|hồ bơi", "cool|/ku:l/|(adj)|mát mẻ, ngầu", "tool|/tu:l/|(n)|công cụ", "fool|/fu:l/|(n)|kẻ ngốc", "school|/sku:l/|(n)|trường học", "do|/du:/|(v)|làm"] },
            { id: "e", phonetic: "e", type: "Short Vowel", examples: ["pen|/pen/|(n)|cây bút", "ten|/ten/|(n)|số mười", "men|/men/|(n)|những người đàn ông", "bed|/bed/|(n)|cái giường", "red|/red/|(adj)|màu đỏ", "leg|/leg/|(n)|cái chân", "get|/get/|(v)|lấy, có được", "let|/let/|(v)|để cho", "met|/met/|(v)|đã gặp (quá khứ của meet)", "set|/set/|(v)|đặt, thiết lập", "pet|/pet/|(n)|thú cưng", "wet|/wet/|(adj)|ướt", "yet|/jet/|(adv)|chưa", "yes|/jes/|(adv)|vâng, có", "tell|/tel/|(v)|nói, kể"] },
            { id: "schwa", phonetic: "ə", type: "Short Vowel (Schwa)", examples: ["a|/ə/|(art)|một", "an|/ən/|(art)|một", "the|/ðə/|(art)|cái, con, người", "to|/tə/|(prep)|đến", "of|/əv/|(prep)|của", "and|/ənd/|(conj)|và", "that|/ðət/|(conj)|rằng", "than|/ðən/|(conj)|hơn", "but|/bət/|(conj)|nhưng", "some|/səm/|(det)|một vài", "about|/əˈbaʊt/|(prep)|về, khoảng", "again|/əˈgen/|(adv)|lại", "away|/əˈweɪ/|(adv)|xa, đi xa", "along|/əˈlɒŋ/|(prep)|dọc theo", "around|/əˈraʊnd/|(prep)|xung quanh"] },
            { id: "er", phonetic: "ɜ:", type: "Long Vowel", examples: ["her|/hɜ:/|(pro)|cô ấy", "term|/tɜ:m/|(n)|thuật ngữ, học kỳ", "verb|/vɜ:b/|(n)|động từ", "serve|/sɜ:v/|(v)|phục vụ", "person|/ˈpɜ:sən/|(n)|người", "perfect|/ˈpɜ:fɪkt/|(adj)|hoàn hảo", "certain|/ˈsɜ:tən/|(adj)|chắc chắn", "sir|/sɜ:/|(n)|ngài", "bird|/bɜ:d/|(n)|con chim", "girl|/gɜ:l/|(n)|cô gái", "first|/fɜ:st/|(adj)|đầu tiên", "third|/θɜ:d/|(adj)|thứ ba", "shirt|/ʃɜ:t/|(n)|áo sơ mi", "skirt|/skɜ:t/|(n)|váy", "dirty|/ˈdɜ:ti/|(adj)|bẩn"] },
            { id: "o-long", phonetic: "ɔ:", type: "Long Vowel", examples: ["or|/ɔ:/|(conj)|hoặc", "for|/fɔ:/|(prep)|cho", "more|/mɔ:/|(adj)|thêm nữa", "store|/stɔ:/|(n)|cửa hàng", "before|/bɪˈfɔ:/|(prep)|trước khi", "score|/skɔ:/|(n)|điểm số", "sport|/spɔ:t/|(n)|thể thao", "short|/ʃɔ:t/|(adj)|ngắn", "port|/pɔ:t/|(n)|cảng", "sort|/sɔ:t/|(n)|loại", "horse|/hɔ:s/|(n)|con ngựa", "force|/fɔ:s/|(n)|lực lượng", "morning|/ˈmɔ:nɪŋ/|(n)|buổi sáng", "north|/nɔ:θ/|(n)|phía bắc", "door|/dɔ:/|(n)|cánh cửa"] },
            { id: "ae", phonetic: "æ", type: "Short Vowel", examples: ["at|/æt/|(prep)|tại", "am|/æm/|(v)|là", "an|/æn/|(art)|một", "as|/æz/|(conj)|như", "and|/ænd/|(conj)|và", "apple|/ˈæpəl/|(n)|quả táo", "ant|/ænt/|(n)|con kiến", "animal|/ˈænɪməl/|(n)|động vật", "angry|/ˈæŋgri/|(adj)|tức giận", "act|/ækt/|(v)|hành động", "bad|/bæd/|(adj)|tồi tệ", "sad|/sæd/|(adj)|buồn", "mad|/mæd/|(adj)|điên, tức giận", "glad|/glæd/|(adj)|vui mừng", "bag|/bæg/|(n)|cái túi"] },
            { id: "cup", phonetic: "ʌ", type: "Short Vowel", examples: ["up|/ʌp/|(adv)|lên", "us|/ʌs/|(pro)|chúng tôi", "cup|/kʌp/|(n)|cái cốc", "bus|/bʌs/|(n)|xe buýt", "cut|/kʌt/|(v)|cắt", "but|/bʌt/|(conj)|nhưng", "hut|/hʌt/|(n)|túp lều", "nut|/nʌt/|(n)|hạt", "shut|/ʃʌt/|(v)|đóng", "rub|/rʌb/|(v)|chà xát", "club|/klʌb/|(n)|câu lạc bộ", "tub|/tʌb/|(n)|bồn tắm", "mud|/mʌd/|(n)|bùn", "bug|/bʌg/|(n)|con bọ", "hug|/hʌg/|(v)|ôm"] },
            { id: "a-long", phonetic: "ɑ:", type: "Long Vowel", examples: ["car|/kɑ:/|(n)|xe hơi", "far|/fɑ:/|(adj)|xa", "star|/stɑ:/|(n)|ngôi sao", "bar|/bɑ:/|(n)|quán bar", "jar|/dʒɑ:/|(n)|cái lọ", "hard|/hɑ:d/|(adj)|cứng, khó", "yard|/jɑ:d/|(n)|cái sân", "card|/kɑ:d/|(n)|thẻ", "part|/pɑ:t/|(n)|phần", "art|/ɑ:t/|(n)|nghệ thuật", "start|/stɑ:t/|(v)|bắt đầu", "smart|/smɑ:t/|(adj)|thông minh", "chart|/tʃɑ:t/|(n)|biểu đồ", "heart|/hɑ:t/|(n)|trái tim", "dark|/dɑ:k/|(adj)|tối"] },
            { id: "o-short", phonetic: "ɒ", type: "Short Vowel", examples: ["on|/ɒn/|(prep)|trên", "off|/ɒf/|(adv)|tắt, khỏi", "of|/ɒv/|(prep)|của", "often|/ˈɒfən/|(adv)|thường xuyên", "hot|/hɒt/|(adj)|nóng", "lot|/lɒt/|(n)|nhiều", "not|/nɒt/|(adv)|không", "got|/gɒt/|(v)|đã có (quá khứ của get)", "pot|/pɒt/|(n)|cái nồi", "dot|/dɒt/|(n)|dấu chấm", "top|/tɒp/|(n)|đỉnh", "stop|/stɒp/|(v)|dừng lại", "shop|/ʃɒp/|(n)|cửa hàng", "drop|/drɒp/|(v)|rơi, làm rớt", "cop|/kɒp/|(n)|cảnh sát"] }
        ],
        diphthongs: [
            { id: "ia", phonetic: "ɪə", type: "Diphthong", examples: ["here|/hɪə/|(adv)|ở đây", "mere|/mɪə/|(adj)|chỉ là", "sphere|/sfɪə/|(n)|hình cầu", "ear|/ɪə/|(n)|tai", "hear|/hɪə/|(v)|nghe", "near|/nɪə/|(adj)|gần", "dear|/dɪə/|(adj)|thân mến", "fear|/fɪə/|(n)|nỗi sợ", "clear|/klɪə/|(adj)|rõ ràng", "year|/jɪə/|(n)|năm", "tear|/tɪə/|(n)|nước mắt", "gear|/gɪə/|(n)|bánh răng", "beard|/bɪəd/|(n)|râu", "weird|/wɪəd/|(adj)|kỳ lạ", "pierce|/pɪəs/|(v)|xuyên qua"] },
            { id: "ei", phonetic: "eɪ", type: "Diphthong", examples: ["day|/deɪ/|(n)|ngày", "say|/seɪ/|(v)|nói", "way|/weɪ/|(n)|đường, cách", "may|/meɪ/|(v)|có thể", "pay|/peɪ/|(v)|trả tiền", "play|/pleɪ/|(v)|chơi", "stay|/steɪ/|(v)|ở lại", "tray|/treɪ/|(n)|cái khay", "gray|/greɪ/|(adj)|màu xám", "pray|/preɪ/|(v)|cầu nguyện", "wait|/weɪt/|(v)|đợi", "rain|/reɪn/|(n)|mưa", "train|/treɪn/|(n)|chuyến tàu", "main|/meɪn/|(adj)|chính", "pain|/peɪn/|(n)|nỗi đau"] },
            { id: "ua", phonetic: "ʊə", type: "Diphthong", examples: ["tour|/tʊə/|(n)|chuyến du lịch", "tourist|/ˈtʊərɪst/|(n)|du khách", "tournament|/ˈtʊənəmənt/|(n)|giải đấu", "pure|/pjʊə/|(adj)|tinh khiết", "cure|/kjʊə/|(v)|chữa trị", "sure|/ʃʊə/|(adj)|chắc chắn", "ensure|/ɪnˈʃʊə/|(v)|đảm bảo", "insure|/ɪnˈʃʊə/|(v)|bảo hiểm", "secure|/sɪˈkjʊə/|(adj)|an toàn", "obscure|/əbˈskjʊə/|(adj)|mờ mịt", "poor|/pʊə/|(adj)|nghèo", "moor|/mʊə/|(n)|vùng đầm lầy", "boor|/bʊə/|(n)|kẻ cục súc", "lure|/lʊə/|(v)|quyến rũ", "allure|/əˈlʊə/|(n)|sức hấp dẫn"] },
            { id: "oi", phonetic: "ɔɪ", type: "Diphthong", examples: ["boy|/bɔɪ/|(n)|cậu bé", "toy|/tɔɪ/|(n)|đồ chơi", "joy|/dʒɔɪ/|(n)|niềm vui", "enjoy|/ɪnˈdʒɔɪ/|(v)|thưởng thức", "employ|/ɪmˈplɔɪ/|(v)|thuê, mướn", "annoy|/əˈnɔɪ/|(v)|làm phiền", "destroy|/dɪˈstrɔɪ/|(v)|phá hủy", "oil|/ɔɪl/|(n)|dầu", "boil|/bɔɪl/|(v)|sôi, luộc", "spoil|/spɔɪl/|(v)|làm hỏng", "foil|/fɔɪl/|(n)|giấy bạc", "coil|/kɔɪl/|(n)|cuộn", "soil|/sɔɪl/|(n)|đất", "join|/dʒɔɪn/|(v)|tham gia", "coin|/kɔɪn/|(n)|đồng xu"] },
            { id: "ou", phonetic: "əʊ", type: "Diphthong", examples: ["no|/nəʊ/|(adv)|không", "go|/gəʊ/|(v)|đi", "so|/səʊ/|(adv)|vì vậy", "old|/əʊld/|(adj)|cũ, già", "cold|/kəʊld/|(adj)|lạnh", "hold|/həʊld/|(v)|cầm, nắm", "gold|/gəʊld/|(n)|vàng", "sold|/səʊld/|(v)|đã bán (quá khứ của sell)", "told|/təʊld/|(v)|đã nói (quá khứ của tell)", "home|/həʊm/|(n)|nhà", "hope|/həʊp/|(v)|hy vọng", "rope|/rəʊp/|(n)|sợi dây", "joke|/dʒəʊk/|(n)|trò đùa", "smoke|/sməʊk/|(v)|hút thuốc", "woke|/wəʊk/|(v)|đã thức dậy (quá khứ của wake)"] },
            { id: "ea", phonetic: "eə", type: "Diphthong", examples: ["care|/keə/|(v)|quan tâm", "dare|/deə/|(v)|dám", "bare|/beə/|(adj)|trần trụi", "rare|/reə/|(adj)|hiếm", "share|/ʃeə/|(v)|chia sẻ", "square|/skweə/|(n)|hình vuông", "compare|/kəmˈpeə/|(v)|so sánh", "prepare|/prɪˈpeə/|(v)|chuẩn bị", "aware|/əˈweə/|(adj)|nhận thức", "software|/ˈsɒftweə/|(n)|phần mềm", "air|/eə/|(n)|không khí", "hair|/heə/|(n)|tóc", "chair|/tʃeə/|(n)|cái ghế", "fair|/feə/|(adj)|công bằng", "pair|/peə/|(n)|cặp, đôi"] },
            { id: "ai", phonetic: "aɪ", type: "Diphthong", examples: ["I|/aɪ/|(pro)|tôi", "my|/maɪ/|(pro)|của tôi", "by|/baɪ/|(prep)|bởi", "cry|/kraɪ/|(v)|khóc", "dry|/draɪ/|(adj)|khô", "fly|/flaɪ/|(v)|bay", "sky|/skaɪ/|(n)|bầu trời", "try|/traɪ/|(v)|thử, cố gắng", "why|/waɪ/|(adv)|tại sao", "eye|/aɪ/|(n)|mắt", "die|/daɪ/|(v)|chết", "lie|/laɪ/|(v)|nói dối, nằm", "tie|/taɪ/|(v)|buộc, thắt", "pie|/paɪ/|(n)|bánh phai", "high|/haɪ/|(adj)|cao"] },
            { id: "au", phonetic: "aʊ", type: "Diphthong", examples: ["how|/haʊ/|(adv)|như thế nào", "now|/naʊ/|(adv)|bây giờ", "cow|/kaʊ/|(n)|con bò", "wow|/waʊ/|(int)|chà, ồ", "bow|/baʊ/|(v)|cúi chào", "allow|/əˈlaʊ/|(v)|cho phép", "brown|/braʊn/|(adj)|màu nâu", "down|/daʊn/|(adv)|xuống", "town|/taʊn/|(n)|thị trấn", "clown|/klaʊn/|(n)|chú hề", "crowd|/kraʊd/|(n)|đám đông", "powder|/ˈpaʊdər/|(n)|bột", "power|/ˈpaʊər/|(n)|sức mạnh", "tower|/ˈtaʊər/|(n)|tòa tháp", "flower|/ˈflaʊər/|(n)|bông hoa"] }
        ]
    },
    consonants: [
        { id: "p", phonetic: "p", type: "Unvoiced Consonant", voiced: false, 
            examplesInitial: ["pen|/pen/|(n)|cây bút", "pan|/pæn/|(n)|cái chảo", "pig|/pɪg/|(n)|con lợn", "pet|/pet/|(n)|thú cưng", "put|/pʊt/|(v)|đặt, để", "push|/pʊʃ/|(v)|đẩy", "pull|/pʊl/|(v)|kéo", "play|/pleɪ/|(v)|chơi", "plan|/plæn/|(n)|kế hoạch", "place|/pleɪs/|(n)|nơi chốn", "paper|/ˈpeɪpər/|(n)|giấy", "people|/ˈpi:pəl/|(n)|mọi người", "part|/pɑ:t/|(n)|phần", "pass|/pɑ:s/|(v)|vượt qua", "pink|/pɪŋk/|(adj)|màu hồng"],
            examplesMedial: ["happy|/ˈhæpi/|(adj)|hạnh phúc", "paper|/ˈpeɪpər/|(n)|giấy", "open|/ˈəʊpən/|(v)|mở", "apple|/ˈæpəl/|(n)|quả táo", "report|/rɪˈpɔ:t/|(n)|báo cáo", "important|/ɪmˈpɔ:tənt/|(adj)|quan trọng", "happen|/ˈhæpən/|(v)|xảy ra", "copy|/ˈkɒpi/|(v)|sao chép", "simple|/ˈsɪmpəl/|(adj)|đơn giản", "support|/səˈpɔ:t/|(v)|ủng hộ", "couple|/ˈkʌpəl/|(n)|cặp đôi", "super|/ˈsu:pər/|(adj)|siêu", "supper|/ˈsʌpər/|(n)|bữa tối", "apply|/əˈplaɪ/|(v)|áp dụng", "depend|/dɪˈpend/|(v)|phụ thuộc"],
            examplesFinal: ["top|/tɒp/|(n)|đỉnh", "hop|/hɒp/|(v)|nhảy lò cò", "cup|/kʌp/|(n)|cái cốc", "cap|/kæp/|(n)|mũ lưỡi trai", "map|/mæp/|(n)|bản đồ", "help|/help/|(v)|giúp đỡ", "sleep|/sli:p/|(v)|ngủ", "deep|/di:p/|(adj)|sâu", "keep|/ki:p/|(v)|giữ", "cheap|/tʃi:p/|(adj)|rẻ", "ship|/ʃɪp/|(n)|con tàu", "shop|/ʃɒp/|(n)|cửa hàng", "drop|/drɒp/|(v)|rơi", "trip|/trɪp/|(n)|chuyến đi", "step|/step/|(n)|bước đi"]
        },
        { id: "b", phonetic: "b", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["big|/bɪg/|(adj)|to lớn", "boy|/bɔɪ/|(n)|cậu bé", "bed|/bed/|(n)|cái giường", "bad|/bæd/|(adj)|tệ", "bag|/bæg/|(n)|cái túi", "box|/bɒks/|(n)|cái hộp", "book|/bʊk/|(n)|quyển sách", "bus|/bʌs/|(n)|xe buýt", "but|/bʌt/|(conj)|nhưng", "by|/baɪ/|(prep)|bởi", "baby|/ˈbeɪbi/|(n)|em bé", "bird|/bɜ:d/|(n)|con chim", "best|/best/|(adj)|tốt nhất", "back|/bæk/|(adv)|trở lại", "bank|/bæŋk/|(n)|ngân hàng"],
            examplesMedial: ["about|/əˈbaʊt/|(prep)|về, khoảng", "baby|/ˈbeɪbi/|(n)|em bé", "table|/ˈteɪbəl/|(n)|cái bàn", "maybe|/ˈmeɪbi/|(adv)|có lẽ", "member|/ˈmembər/|(n)|thành viên", "public|/ˈpʌblɪk/|(adj)|công cộng", "problem|/ˈprɒbləm/|(n)|vấn đề", "rabbit|/ˈræbɪt/|(n)|con thỏ", "nobody|/ˈnəʊbədi/|(pro)|không ai", "habit|/ˈhæbɪt/|(n)|thói quen", "ribbon|/ˈrɪbən/|(n)|ruy băng", "label|/ˈleɪbəl/|(n)|nhãn", "robot|/ˈrəʊbɒt/|(n)|người máy", "carbon|/ˈkɑ:bən/|(n)|các-bon", "fiber|/ˈfaɪbər/|(n)|chất xơ"],
            examplesFinal: ["cab|/kæb/|(n)|xe taxi", "web|/web/|(n)|mạng nhện", "job|/dʒɒb/|(n)|công việc", "rob|/rɒb/|(v)|cướp", "mob|/mɒb/|(n)|đám đông", "club|/klʌb/|(n)|câu lạc bộ", "tub|/tʌb/|(n)|bồn tắm", "rub|/rʌb/|(v)|chà xát", "pub|/pʌb/|(n)|quán rượu", "grab|/græb/|(v)|vồ lấy", "crab|/kræb/|(n)|con cua", "globe|/gləʊb/|(n)|quả địa cầu", "tube|/tju:b/|(n)|cái ống", "cube|/kju:b/|(n)|khối lập phương", "probe|/prəʊb/|(n)|máy dò"]
        },
        { id: "t", phonetic: "t", type: "Unvoiced Consonant", voiced: false, 
            examplesInitial: ["time|/taɪm/|(n)|thời gian", "tea|/ti:/|(n)|trà", "two|/tu:/|(n)|số hai", "ten|/ten/|(n)|số mười", "top|/tɒp/|(n)|đỉnh", "take|/teɪk/|(v)|lấy", "talk|/tɔ:k/|(v)|nói chuyện", "tell|/tel/|(v)|kể, bảo", "test|/test/|(n)|bài kiểm tra", "town|/taʊn/|(n)|thị trấn", "today|/təˈdeɪ/|(adv)|hôm nay", "teacher|/ˈti:tʃər/|(n)|giáo viên", "tall|/tɔ:l/|(adj)|cao", "table|/ˈteɪbəl/|(n)|cái bàn", "toy|/tɔɪ/|(n)|đồ chơi"],
            examplesMedial: ["water|/ˈwɔ:tər/|(n)|nước", "better|/ˈbetər/|(adj)|tốt hơn", "letter|/ˈletər/|(n)|bức thư", "little|/ˈlɪtəl/|(adj)|nhỏ", "city|/ˈsɪti/|(n)|thành phố", "after|/ˈɑ:ftər/|(prep)|sau khi", "matter|/ˈmætər/|(n)|vấn đề", "doctor|/ˈdɒktər/|(n)|bác sĩ", "center|/ˈsentər/|(n)|trung tâm", "winter|/ˈwɪntər/|(n)|mùa đông", "bottle|/ˈbɒtəl/|(n)|cái chai", "bottom|/ˈbɒtəm/|(n)|đáy", "butter|/ˈbʌtər/|(n)|bơ", "button|/ˈbʌtən/|(n)|cái nút", "metal|/ˈmetəl/|(n)|kim loại"],
            examplesFinal: ["it|/ɪt/|(pro)|nó", "at|/æt/|(prep)|tại", "out|/aʊt/|(adv)|ra ngoài", "but|/bʌt/|(conj)|nhưng", "not|/nɒt/|(adv)|không", "get|/get/|(v)|có được", "let|/let/|(v)|để", "met|/met/|(v)|đã gặp", "set|/set/|(v)|đặt", "hit|/hɪt/|(v)|đánh", "sit|/sɪt/|(v)|ngồi", "fit|/fɪt/|(adj)|vừa vặn", "cat|/kæt/|(n)|con mèo", "hat|/hæt/|(n)|cái mũ", "fat|/fæt/|(adj)|mập"]
        },
        { id: "d", phonetic: "d", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["day|/deɪ/|(n)|ngày", "dog|/dɒg/|(n)|con chó", "do|/du:/|(v)|làm", "did|/dɪd/|(v)|đã làm", "done|/dʌn/|(v)|hoàn thành", "down|/daʊn/|(adv)|xuống", "door|/dɔ:/|(n)|cánh cửa", "desk|/desk/|(n)|bàn làm việc", "deep|/di:p/|(adj)|sâu", "dark|/dɑ:k/|(adj)|tối", "duck|/dʌk/|(n)|con vịt", "doll|/dɒl/|(n)|búp bê", "dance|/dɑ:ns/|(v)|nhảy múa", "drink|/drɪŋk/|(v)|uống", "drive|/draɪv/|(v)|lái xe"],
            examplesMedial: ["under|/ˈʌndər/|(prep)|dưới", "ready|/ˈredi/|(adj)|sẵn sàng", "reading|/ˈri:dɪŋ/|(n)|việc đọc", "window|/ˈwɪndəʊ/|(n)|cửa sổ", "body|/ˈbɒdi/|(n)|cơ thể", "today|/təˈdeɪ/|(adv)|hôm nay", "middle|/ˈmɪdəl/|(n)|giữa", "garden|/ˈgɑ:dən/|(n)|khu vườn", "sudden|/ˈsʌdən/|(adj)|đột ngột", "shadow|/ˈʃædəʊ/|(n)|bóng râm", "lady|/ˈleɪdi/|(n)|quý cô", "shoulder|/ˈʃəʊldər/|(n)|bờ vai", "model|/ˈmɒdəl/|(n)|mô hình", "ladder|/ˈlædər/|(n)|cái thang", "leader|/ˈli:dər/|(n)|lãnh đạo"],
            examplesFinal: ["bad|/bæd/|(adj)|tệ", "bed|/bed/|(n)|cái giường", "sad|/sæd/|(adj)|buồn", "mad|/mæd/|(adj)|tức giận", "glad|/glæd/|(adj)|vui mừng", "had|/hæd/|(v)|đã có", "good|/gʊd/|(adj)|tốt", "food|/fu:d/|(n)|thức ăn", "wood|/wʊd/|(n)|gỗ", "head|/hed/|(n)|cái đầu", "read|/ri:d/|(v)|đọc", "red|/red/|(adj)|màu đỏ", "need|/ni:d/|(v)|cần", "feed|/fi:d/|(v)|cho ăn", "seed|/si:d/|(n)|hạt giống"]
        },
        { id: "ch", phonetic: "tʃ", type: "Unvoiced Consonant", voiced: false, 
            examplesInitial: ["chair|/tʃeə/|(n)|cái ghế", "child|/tʃaɪld/|(n)|đứa trẻ", "children|/ˈtʃɪldrən/|(n)|những đứa trẻ", "cheese|/tʃi:z/|(n)|phô mai", "cheap|/tʃi:p/|(adj)|rẻ", "check|/tʃek/|(v)|kiểm tra", "church|/tʃɜ:tʃ/|(n)|nhà thờ", "choose|/tʃu:z/|(v)|chọn lựa", "change|/tʃeɪndʒ/|(v)|thay đổi", "chance|/tʃɑ:ns/|(n)|cơ hội", "chicken|/ˈtʃɪkɪn/|(n)|con gà", "chip|/tʃɪp/|(n)|khoai tây chiên", "chin|/tʃɪn/|(n)|cái cằm", "chat|/tʃæt/|(v)|trò chuyện", "cheat|/tʃi:t/|(v)|gian lận"],
            examplesMedial: ["teacher|/ˈti:tʃər/|(n)|giáo viên", "kitchen|/ˈkɪtʃɪn/|(n)|nhà bếp", "picture|/ˈpɪktʃər/|(n)|bức tranh", "nature|/ˈneɪtʃər/|(n)|tự nhiên", "future|/ˈfju:tʃər/|(n)|tương lai", "matching|/ˈmætʃɪŋ/|(adj)|phù hợp", "catching|/ˈkætʃɪŋ/|(adj)|bắt lây", "watching|/ˈwɒtʃɪŋ/|(v)|đang xem", "touching|/ˈtʌtʃɪŋ/|(adj)|cảm động", "feature|/ˈfi:tʃər/|(n)|tính năng", "culture|/ˈkʌltʃər/|(n)|văn hóa", "century|/ˈsentʃəri/|(n)|thế kỷ", "fortune|/ˈfɔ:tʃu:n/|(n)|vận may", "capture|/ˈkæptʃər/|(v)|bắt giữ", "creature|/ˈkri:tʃər/|(n)|sinh vật"],
            examplesFinal: ["much|/mʌtʃ/|(adv)|nhiều", "such|/sʌtʃ/|(adj)|như vậy", "rich|/rɪtʃ/|(adj)|giàu có", "which|/wɪtʃ/|(pro)|cái nào", "catch|/kætʃ/|(v)|bắt lấy", "match|/mætʃ/|(n)|trận đấu", "watch|/wɒtʃ/|(v)|xem", "touch|/tʌtʃ/|(v)|chạm", "teach|/ti:tʃ/|(v)|dạy", "beach|/bi:tʃ/|(n)|bãi biển", "speech|/spi:tʃ/|(n)|bài phát biểu", "reach|/ri:tʃ/|(v)|vươn tới", "coach|/kəʊtʃ/|(n)|huấn luyện viên", "branch|/brɑ:ntʃ/|(n)|nhánh, chi nhánh", "lunch|/lʌntʃ/|(n)|bữa trưa"]
        },
        { id: "j", phonetic: "dʒ", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["job|/dʒɒb/|(n)|công việc", "joy|/dʒɔɪ/|(n)|niềm vui", "joke|/dʒəʊk/|(n)|trò đùa", "jump|/dʒʌmp/|(v)|nhảy", "just|/dʒʌst/|(adv)|chỉ, vừa mới", "join|/dʒɔɪn/|(v)|tham gia", "juice|/dʒu:s/|(n)|nước ép", "july|/dʒuˈlaɪ/|(n)|tháng bảy", "june|/dʒu:n/|(n)|tháng sáu", "judge|/dʒʌdʒ/|(n)|thẩm phán", "jacket|/ˈdʒækɪt/|(n)|áo khoác", "jar|/dʒɑ:/|(n)|cái lọ", "jam|/dʒæm/|(n)|mứt", "jet|/dʒet/|(n)|máy bay phản lực", "jelly|/ˈdʒeli/|(n)|thạch"],
            examplesMedial: ["magic|/ˈmædʒɪk/|(n)|ma thuật", "energy|/ˈenədʒi/|(n)|năng lượng", "engine|/ˈendʒɪn/|(n)|động cơ", "danger|/ˈdeɪndʒər/|(n)|sự nguy hiểm", "soldier|/ˈsəʊldʒər/|(n)|người lính", "object|/ˈɒbdʒɪkt/|(n)|vật thể", "subject|/ˈsʌbdʒɪkt/|(n)|chủ đề", "major|/ˈmeɪdʒər/|(adj)|chính, lớn", "imagine|/ɪˈmædʒɪn/|(v)|tưởng tượng", "passenger|/ˈpæsɪndʒər/|(n)|hành khách", "stranger|/ˈstreɪndʒər/|(n)|người lạ", "suggest|/səˈdʒest/|(v)|đề nghị", "margin|/ˈmɑ:dʒɪn/|(n)|lề", "logic|/ˈlɒdʒɪk/|(n)|lý luận", "budget|/ˈbʌdʒɪt/|(n)|ngân sách"],
            examplesFinal: ["page|/peɪdʒ/|(n)|trang", "age|/eɪdʒ/|(n)|tuổi", "cage|/keɪdʒ/|(n)|cái lồng", "stage|/steɪdʒ/|(n)|sân khấu", "large|/lɑ:dʒ/|(adj)|rộng lớn", "huge|/hju:dʒ/|(adj)|to lớn", "bridge|/brɪdʒ/|(n)|cây cầu", "edge|/edʒ/|(n)|rìa, cạnh", "knowledge|/ˈnɒlɪdʒ/|(n)|kiến thức", "college|/ˈkɒlɪdʒ/|(n)|trường cao đẳng", "village|/ˈvɪlɪdʒ/|(n)|ngôi làng", "language|/ˈlæŋgwɪdʒ/|(n)|ngôn ngữ", "message|/ˈmesɪdʒ/|(n)|tin nhắn", "manage|/ˈmænɪdʒ/|(v)|quản lý", "damage|/ˈdæmɪdʒ/|(n)|sự thiệt hại"]
        },
        { id: "k", phonetic: "k", type: "Unvoiced Consonant", voiced: false, 
            examplesInitial: ["car|/kɑ:/|(n)|xe hơi", "cat|/kæt/|(n)|con mèo", "key|/ki:/|(n)|chìa khóa", "keep|/ki:p/|(v)|giữ", "kind|/kaɪnd/|(adj)|tử tế", "kill|/kɪl/|(v)|giết", "kick|/kɪk/|(v)|đá", "cup|/kʌp/|(n)|cái cốc", "come|/kʌm/|(v)|đến", "call|/kɔ:l/|(v)|gọi", "cold|/kəʊld/|(adj)|lạnh", "clean|/kli:n/|(adj)|sạch sẽ", "class|/klɑ:s/|(n)|lớp học", "card|/kɑ:d/|(n)|thẻ", "cash|/kæʃ/|(n)|tiền mặt"],
            examplesMedial: ["pocket|/ˈpɒkɪt/|(n)|túi áo", "ticket|/ˈtɪkɪt/|(n)|vé", "monkey|/ˈmʌŋki/|(n)|con khỉ", "doctor|/ˈdɒktər/|(n)|bác sĩ", "actor|/ˈæktər/|(n)|diễn viên", "breakfast|/ˈbrekfəst/|(n)|bữa sáng", "second|/ˈsekənd/|(n)|giây, thứ hai", "local|/ˈləʊkəl/|(adj)|địa phương", "market|/ˈmɑ:kɪt/|(n)|chợ", "jacket|/ˈdʒækɪt/|(n)|áo khoác", "record|/ˈrekɔ:d/|(n)|bản ghi", "secret|/ˈsi:krɪt/|(n)|bí mật", "weekend|/ˌwi:kˈend/|(n)|cuối tuần", "welcome|/ˈwelkəm/|(adj)|chào mừng", "chicken|/ˈtʃɪkɪn/|(n)|con gà"],
            examplesFinal: ["back|/bæk/|(adv)|trở lại", "black|/blæk/|(adj)|màu đen", "pack|/pæk/|(v)|đóng gói", "sick|/sɪk/|(adj)|ốm", "pick|/pɪk/|(v)|nhặt", "kick|/kɪk/|(v)|đá", "quick|/kwɪk/|(adj)|nhanh", "clock|/klɒk/|(n)|đồng hồ", "lock|/lɒk/|(n)|ổ khóa", "rock|/rɒk/|(n)|đá", "book|/bʊk/|(n)|sách", "look|/lʊk/|(v)|nhìn", "took|/tʊk/|(v)|đã lấy", "cook|/kʊk/|(v)|nấu", "hook|/hʊk/|(n)|cái móc"]
        },
        { id: "g", phonetic: "g", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["go|/gəʊ/|(v)|đi", "get|/get/|(v)|có được", "good|/gʊd/|(adj)|tốt", "girl|/gɜ:l/|(n)|cô gái", "give|/gɪv/|(v)|cho", "game|/geɪm/|(n)|trò chơi", "garden|/ˈgɑ:dən/|(n)|khu vườn", "gate|/geɪt/|(n)|cái cổng", "guess|/ges/|(v)|đoán", "guest|/gest/|(n)|khách", "glass|/glɑ:s/|(n)|kính, ly", "green|/gri:n/|(adj)|xanh lá", "group|/gru:p/|(n)|nhóm", "grow|/grəʊ/|(v)|phát triển", "grass|/grɑ:s/|(n)|cỏ"],
            examplesMedial: ["again|/əˈgen/|(adv)|lại", "begin|/bɪˈgɪn/|(v)|bắt đầu", "sugar|/ˈʃʊgər/|(n)|đường", "tiger|/ˈtaɪgər/|(n)|con hổ", "forget|/fəˈget/|(v)|quên", "figure|/ˈfɪgər/|(n)|hình dáng, con số", "program|/ˈprəʊgræm/|(n)|chương trình", "together|/təˈgeðər/|(adv)|cùng nhau", "hungry|/ˈhʌŋgri/|(adj)|đói", "angry|/ˈæŋgri/|(adj)|tức giận", "legal|/ˈli:gəl/|(adj)|hợp pháp", "dragon|/ˈdrægən/|(n)|con rồng", "regular|/ˈregjʊlər/|(adj)|đều đặn", "target|/ˈtɑ:gɪt/|(n)|mục tiêu", "burger|/ˈbɜ:gər/|(n)|bánh mì kẹp thịt"],
            examplesFinal: ["big|/bɪg/|(adj)|lớn", "pig|/pɪg/|(n)|con lợn", "dig|/dɪg/|(v)|đào", "bag|/bæg/|(n)|cái túi", "leg|/leg/|(n)|cái chân", "egg|/eg/|(n)|quả trứng", "dog|/dɒg/|(n)|con chó", "log|/lɒg/|(n)|khúc gỗ", "frog|/frɒg/|(n)|con ếch", "bug|/bʌg/|(n)|con bọ", "hug|/hʌg/|(v)|ôm", "mug|/mʌg/|(n)|cái cốc", "rug|/rʌg/|(n)|tấm thảm", "plug|/plʌg/|(n)|phích cắm", "drag|/dræg/|(v)|kéo lê"]
        },
        { id: "f", phonetic: "f", type: "Unvoiced Consonant", voiced: false, 
            examplesInitial: ["fall|/fɔ:l/|(v)|rơi", "family|/ˈfæməli/|(n)|gia đình", "far|/fɑ:/|(adj)|xa", "fast|/fɑ:st/|(adj)|nhanh", "feel|/fi:l/|(v)|cảm thấy", "few|/fju:/|(det)|một ít", "find|/faɪnd/|(v)|tìm", "first|/fɜ:st/|(adj)|đầu tiên", "five|/faɪv/|(n)|số năm", "food|/fu:d/|(n)|thức ăn", "face|/feɪs/|(n)|khuôn mặt", "fact|/fækt/|(n)|sự thật", "fair|/feə/|(adj)|công bằng", "farm|/fɑ:m/|(n)|nông trại", "father|/ˈfɑ:ðər/|(n)|cha"],
            examplesMedial: ["after|/ˈɑ:ftər/|(prep)|sau khi", "before|/bɪˈfɔ:/|(prep)|trước", "coffee|/ˈkɒfi/|(n)|cà phê", "office|/ˈɒfɪs/|(n)|văn phòng", "perfect|/ˈpɜ:fɪkt/|(adj)|hoàn hảo", "beautiful|/ˈbju:tɪfəl/|(adj)|đẹp", "careful|/ˈkeəfəl/|(adj)|cẩn thận", "differ|/ˈdɪfər/|(v)|khác biệt", "suffer|/ˈsʌfər/|(v)|chịu đựng", "traffic|/ˈtræfɪk/|(n)|giao thông", "effort|/ˈefət/|(n)|nỗ lực", "comfort|/ˈkʌmfət/|(n)|sự thoải mái", "profit|/ˈprɒfɪt/|(n)|lợi nhuận", "defend|/dɪˈfend/|(v)|bảo vệ", "offer|/ˈɒfər/|(v)|đề nghị"],
            examplesFinal: ["if|/ɪf/|(conj)|nếu", "off|/ɒf/|(adv)|tắt", "half|/hɑ:f/|(n)|một nửa", "life|/laɪf/|(n)|cuộc sống", "wife|/waɪf/|(n)|vợ", "knife|/naɪf/|(n)|con dao", "safe|/seɪf/|(adj)|an toàn", "leaf|/li:f/|(n)|chiếc lá", "chief|/tʃi:f/|(n)|thủ lĩnh", "beef|/bi:f/|(n)|thịt bò", "roof|/ru:f/|(n)|mái nhà", "proof|/pru:f/|(n)|bằng chứng", "laugh|/lɑ:f/|(v)|cười", "enough|/ɪˈnʌf/|(adv)|đủ", "rough|/rʌf/|(adj)|thô ráp"]
        },
        { id: "v", phonetic: "v", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["van|/væn/|(n)|xe tải nhỏ", "vase|/vɑ:z/|(n)|lọ hoa", "very|/ˈveri/|(adv)|rất", "voice|/vɔɪs/|(n)|giọng nói", "visit|/ˈvɪzɪt/|(v)|thăm", "view|/vju:/|(n)|tầm nhìn", "vote|/vəʊt/|(v)|bầu cử", "value|/ˈvælju:/|(n)|giá trị", "village|/ˈvɪlɪdʒ/|(n)|ngôi làng", "valley|/ˈvæli/|(n)|thung lũng", "vacation|/vəˈkeɪʃən/|(n)|kỳ nghỉ", "vast|/vɑ:st/|(adj)|rộng lớn", "vegetable|/ˈvedʒtəbəl/|(n)|rau củ", "video|/ˈvɪdiəʊ/|(n)|video", "vowel|/ˈvaʊəl/|(n)|nguyên âm"],
            examplesMedial: ["over|/ˈəʊvər/|(prep)|trên, qua", "never|/ˈnevər/|(adv)|không bao giờ", "ever|/ˈevər/|(adv)|từng", "every|/ˈevri/|(det)|mỗi", "seven|/ˈsevən/|(n)|số bảy", "even|/ˈi:vən/|(adv)|thậm chí", "travel|/ˈtrævəl/|(v)|du lịch", "river|/ˈrɪvər/|(n)|con sông", "heavy|/ˈhevi/|(adj)|nặng", "cover|/ˈkʌvər/|(v)|che phủ", "movie|/ˈmu:vi/|(n)|bộ phim", "level|/ˈlevəl/|(n)|cấp độ", "evening|/ˈi:vnɪŋ/|(n)|buổi tối", "clever|/ˈklevər/|(adj)|thông minh", "service|/ˈsɜ:vɪs/|(n)|dịch vụ"],
            examplesFinal: ["have|/hæv/|(v)|có", "give|/gɪv/|(v)|cho", "live|/lɪv/|(v)|sống", "leave|/li:v/|(v)|rời đi", "love|/lʌv/|(n)|tình yêu", "move|/mu:v/|(v)|di chuyển", "prove|/pru:v/|(v)|chứng minh", "save|/seɪv/|(v)|cứu, lưu", "wave|/weɪv/|(n)|sóng", "cave|/keɪv/|(n)|hang động", "drive|/draɪv/|(v)|lái xe", "five|/faɪv/|(n)|số năm", "alive|/əˈlaɪv/|(adj)|còn sống", "arrive|/əˈraɪv/|(v)|đến nơi", "believe|/bɪˈli:v/|(v)|tin tưởng"]
        },
        { id: "th-unvoiced", phonetic: "θ", type: "Unvoiced Consonant", voiced: false, 
            examplesInitial: ["thank|/θæŋk/|(v)|cảm ơn", "think|/θɪŋk/|(v)|nghĩ", "thing|/θɪŋ/|(n)|thứ, vật", "thin|/θɪn/|(adj)|mỏng, gầy", "thick|/θɪk/|(adj)|dày", "thief|/θi:f/|(n)|kẻ trộm", "three|/θri:/|(n)|số ba", "throw|/θrəʊ/|(v)|ném", "through|/θru:/|(prep)|xuyên qua", "thumb|/θʌm/|(n)|ngón cái", "third|/θɜ:d/|(adj)|thứ ba", "thirsty|/ˈθɜ:sti/|(adj)|khát", "thirteen|/ˌθɜ:ˈti:n/|(n)|mười ba", "thunder|/ˈθʌndər/|(n)|sấm", "Thursday|/ˈθɜ:zdeɪ/|(n)|thứ năm"],
            examplesMedial: ["nothing|/ˈnʌθɪŋ/|(pro)|không có gì", "anything|/ˈenɪθɪŋ/|(pro)|bất cứ thứ gì", "something|/ˈsʌmθɪŋ/|(pro)|một cái gì đó", "everything|/ˈevriθɪŋ/|(pro)|mọi thứ", "healthy|/ˈhelθi/|(adj)|khỏe mạnh", "wealthy|/ˈwelθi/|(adj)|giàu có", "author|/ˈɔ:θər/|(n)|tác giả", "birthday|/ˈbɜ:θdeɪ/|(n)|sinh nhật", "method|/ˈmeθəd/|(n)|phương pháp", "anthem|/ˈænθəm/|(n)|bài quốc ca", "athlete|/ˈæθli:t/|(n)|vận động viên", "panther|/ˈpænθər/|(n)|báo đen", "bathtub|/ˈbɑ:θtʌb/|(n)|bồn tắm", "faithful|/ˈfeɪθfəl/|(adj)|trung thành", "pathway|/ˈpɑ:θweɪ/|(n)|đường mòn"],
            examplesFinal: ["bath|/bɑ:θ/|(n)|bồn tắm", "path|/pɑ:θ/|(n)|con đường", "math|/mæθ/|(n)|toán học", "mouth|/maʊθ/|(n)|cái miệng", "south|/saʊθ/|(n)|hướng nam", "north|/nɔ:θ/|(n)|hướng bắc", "month|/mʌnθ/|(n)|tháng", "earth|/ɜ:θ/|(n)|trái đất", "health|/helθ/|(n)|sức khỏe", "wealth|/welθ/|(n)|sự giàu có", "death|/deθ/|(n)|cái chết", "breath|/breθ/|(n)|hơi thở", "teeth|/ti:θ/|(n)|răng (số nhiều)", "both|/bəʊθ/|(pro)|cả hai", "truth|/tru:θ/|(n)|sự thật"]
        },
        { id: "th-voiced", phonetic: "ð", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["the|/ðə/|(art)|cái, con", "this|/ðɪs/|(pro)|cái này", "that|/ðæt/|(pro)|cái kia", "these|/ði:z/|(pro)|những cái này", "those|/ðəʊz/|(pro)|những cái kia", "they|/ðeɪ/|(pro)|họ", "them|/ðem/|(pro)|họ (tân ngữ)", "their|/ðeə/|(pro)|của họ", "there|/ðeə/|(adv)|ở đó", "then|/ðen/|(adv)|sau đó", "than|/ðæn/|(conj)|hơn", "though|/ðəʊ/|(conj)|mặc dù", "thus|/ðʌs/|(adv)|do đó", "therefore|/ˈðeəfɔ:/|(adv)|vì vậy", "themselves|/ðəmˈselvz/|(pro)|chính họ"],
            examplesMedial: ["mother|/ˈmʌðər/|(n)|mẹ", "father|/ˈfɑ:ðər/|(n)|cha", "brother|/ˈbrʌðər/|(n)|anh em trai", "weather|/ˈweðər/|(n)|thời tiết", "leather|/ˈleðər/|(n)|da", "together|/təˈgeðər/|(adv)|cùng nhau", "other|/ˈʌðər/|(adj)|khác", "another|/əˈnʌðər/|(adj)|một cái khác", "either|/ˈaɪðər/|(conj)|hoặc", "neither|/ˈnaɪðər/|(conj)|cũng không", "whether|/ˈweðər/|(conj)|liệu", "gather|/ˈgæðər/|(v)|tụ tập", "bother|/ˈbɒðər/|(v)|làm phiền", "feather|/ˈfeðər/|(n)|lông vũ", "clothing|/ˈkləʊðɪŋ/|(n)|quần áo"],
            examplesFinal: ["smooth|/smu:ð/|(adj)|mượt mà", "breathe|/bri:ð/|(v)|thở", "bathe|/beɪð/|(v)|tắm", "clothe|/kləʊð/|(v)|mặc đồ", "soothe|/su:ð/|(v)|xoa dịu", "with|/wɪð/|(prep)|với", "loathe|/ləʊð/|(v)|ghét bỏ", "tithe|/taɪð/|(n)|thuế thập phân", "writhe|/raɪð/|(v)|quằn quại", "scythe|/saɪð/|(n)|lưỡi hái", "mouthe|/maʊð/|(v)|mấp máy môi", "teethe|/ti:ð/|(v)|mọc răng", "lathe|/leɪð/|(n)|máy tiện", "bequeath|/bɪˈkwi:ð/|(v)|để lại, truyền lại", "seethe|/si:ð/|(v)|sôi sục"]
        },
        { id: "s", phonetic: "s", type: "Unvoiced Consonant", voiced: false, 
            examplesInitial: ["see|/si:/|(v)|thấy", "say|/seɪ/|(v)|nói", "so|/səʊ/|(adv)|như vậy", "some|/sʌm/|(det)|vài", "sun|/sʌn/|(n)|mặt trời", "sad|/sæd/|(adj)|buồn", "sit|/sɪt/|(v)|ngồi", "send|/send/|(v)|gửi", "song|/sɒŋ/|(n)|bài hát", "sound|/saʊnd/|(n)|âm thanh", "same|/seɪm/|(adj)|giống", "safe|/seɪf/|(adj)|an toàn", "sail|/seɪl/|(v)|chèo thuyền", "salt|/sɔ:lt/|(n)|muối", "sand|/sænd/|(n)|cát"],
            examplesMedial: ["also|/ˈɔ:lsəʊ/|(adv)|cũng", "answer|/ˈɑ:nsər/|(v)|trả lời", "listen|/ˈlɪsən/|(v)|lắng nghe", "lesson|/ˈlesən/|(n)|bài học", "person|/ˈpɜ:sən/|(n)|người", "missing|/ˈmɪsɪŋ/|(adj)|thất lạc", "message|/ˈmesɪdʒ/|(n)|tin nhắn", "inside|/ɪnˈsaɪd/|(prep)|bên trong", "history|/ˈhɪstəri/|(n)|lịch sử", "outside|/aʊtˈsaɪd/|(prep)|bên ngoài", "passing|/ˈpɑ:sɪŋ/|(adj)|thoáng qua", "classic|/ˈklæsɪk/|(adj)|cổ điển", "custom|/ˈkʌstəm/|(n)|phong tục", "beside|/bɪˈsaɪd/|(prep)|bên cạnh", "music|/ˈmju:zɪk/|(n)|âm nhạc"],
            examplesFinal: ["us|/ʌs/|(pro)|chúng tôi", "bus|/bʌs/|(n)|xe buýt", "yes|/jes/|(adv)|vâng", "this|/ðɪs/|(pro)|cái này", "miss|/mɪs/|(v)|nhớ, lỡ", "kiss|/kɪs/|(v)|hôn", "pass|/pɑ:s/|(v)|vượt qua", "glass|/glɑ:s/|(n)|ly, kính", "class|/klɑ:s/|(n)|lớp học", "grass|/grɑ:s/|(n)|cỏ", "face|/feɪs/|(n)|khuôn mặt", "place|/pleɪs/|(n)|địa điểm", "space|/speɪs/|(n)|không gian", "race|/reɪs/|(n)|cuộc đua", "ice|/aɪs/|(n)|nước đá"]
        },
        { id: "z", phonetic: "z", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["zoo|/zu:/|(n)|sở thú", "zero|/ˈzɪərəʊ/|(n)|số không", "zebra|/ˈzebrə/|(n)|ngựa vằn", "zip|/zɪp/|(v)|kéo khóa", "zone|/zəʊn/|(n)|khu vực", "zombie|/ˈzɒmbi/|(n)|thây ma", "zoom|/zu:m/|(v)|phóng to", "zeal|/zi:l/|(n)|lòng sốt sắng", "zest|/zest/|(n)|sự nhiệt tình", "zigzag|/ˈzɪgzæg/|(adj)|ngoằn ngoèo", "zinc|/zɪŋk/|(n)|kẽm", "zap|/zæp/|(v)|bắn, diệt", "zen|/zen/|(n)|thiền", "zillion|/ˈzɪljən/|(n)|số lượng vô vàn", "zipper|/ˈzɪpər/|(n)|dây kéo"],
            examplesMedial: ["crazy|/ˈkreɪzi/|(adj)|điên rồ", "lazy|/ˈleɪzi/|(adj)|lười biếng", "dizzy|/ˈdɪzi/|(adj)|chóng mặt", "easy|/ˈi:zi/|(adj)|dễ dàng", "busy|/ˈbɪzi/|(adj)|bận rộn", "music|/ˈmju:zɪk/|(n)|âm nhạc", "visit|/ˈvɪzɪt/|(v)|thăm hỏi", "reason|/ˈri:zən/|(n)|lý do", "season|/ˈsi:zən/|(n)|mùa", "thousand|/ˈθaʊzənd/|(n)|nghìn", "present|/ˈprezənt/|(n)|món quà", "wizard|/ˈwɪzəd/|(n)|phù thủy", "cousin|/ˈkʌzən/|(n)|anh em họ", "chosen|/ˈtʃəʊzən/|(v)|được chọn", "desert|/dɪˈzɜ:t/|(v)|bỏ rơi"],
            examplesFinal: ["is|/ɪz/|(v)|là", "his|/hɪz/|(pro)|của anh ấy", "as|/æz/|(conj)|như", "was|/wɒz/|(v)|đã là", "has|/hæz/|(v)|có", "does|/dʌz/|(v)|làm", "goes|/gəʊz/|(v)|đi", "shoes|/ʃu:z/|(n)|giày", "eyes|/aɪz/|(n)|mắt", "boys|/bɔɪz/|(n)|các cậu bé", "girls|/gɜ:lz/|(n)|các cô gái", "toys|/tɔɪz/|(n)|đồ chơi", "days|/deɪz/|(n)|ngày", "ways|/weɪz/|(n)|cách thức", "always|/ˈɔ:lweɪz/|(adv)|luôn luôn"]
        },
        { id: "sh", phonetic: "ʃ", type: "Unvoiced Consonant", voiced: false, 
            examplesInitial: ["she|/ʃi:/|(pro)|cô ấy", "shoe|/ʃu:/|(n)|giày", "shop|/ʃɒp/|(n)|cửa hàng", "ship|/ʃɪp/|(n)|tàu", "shirt|/ʃɜ:t/|(n)|áo sơ mi", "sheep|/ʃi:p/|(n)|con cừu", "shape|/ʃeɪp/|(n)|hình dạng", "share|/ʃeə/|(v)|chia sẻ", "show|/ʃəʊ/|(v)|chỉ ra, biểu diễn", "should|/ʃʊd/|(v)|nên", "short|/ʃɔ:t/|(adj)|ngắn", "shut|/ʃʌt/|(v)|đóng", "shine|/ʃaɪn/|(v)|chiếu sáng", "shell|/ʃel/|(n)|vỏ sò", "shade|/ʃeɪd/|(n)|bóng râm"],
            examplesMedial: ["machine|/məˈʃi:n/|(n)|máy móc", "station|/ˈsteɪʃən/|(n)|trạm, nhà ga", "action|/ˈækʃən/|(n)|hành động", "nation|/ˈneɪʃən/|(n)|quốc gia", "motion|/ˈməʊʃən/|(n)|chuyển động", "patient|/ˈpeɪʃənt/|(adj)|kiên nhẫn", "fashion|/ˈfæʃən/|(n)|thời trang", "ocean|/ˈəʊʃən/|(n)|đại dương", "social|/ˈsəʊʃəl/|(adj)|xã hội", "special|/ˈspeʃəl/|(adj)|đặc biệt", "issue|/ˈɪʃu:/|(n)|vấn đề", "Russian|/ˈrʌʃən/|(n)|người Nga", "pressure|/ˈpreʃər/|(n)|áp lực", "session|/ˈseʃən/|(n)|phiên họp", "washing|/ˈwɒʃɪŋ/|(n)|việc giặt giũ"],
            examplesFinal: ["fish|/fɪʃ/|(n)|cá", "dish|/dɪʃ/|(n)|món ăn, đĩa", "wash|/wɒʃ/|(v)|rửa", "push|/pʊʃ/|(v)|đẩy", "rush|/rʌʃ/|(v)|vội vã", "brush|/brʌʃ/|(v)|chải", "crash|/kræʃ/|(n)|va chạm", "smash|/smæʃ/|(v)|đập vỡ", "flash|/flæʃ/|(n)|tia chớp", "cash|/kæʃ/|(n)|tiền mặt", "dash|/dæʃ/|(v)|lao tới", "trash|/træʃ/|(n)|rác", "fresh|/freʃ/|(adj)|tươi mới", "flesh|/fleʃ/|(n)|thịt (người/động vật)", "wish|/wɪʃ/|(v)|ước"]
        },
        { id: "zh", phonetic: "ʒ", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["genre|/ˈʒɒnrə/|(n)|thể loại", "gendarme|/ˈʒɒndɑ:m/|(n)|cảnh sát Pháp", "jacques|/ʒɑ:k/|(n)|tên Jacques", "gigolo|/ˈʒɪgələʊ/|(n)|trai bao", "jabot|/ˈʒæbəʊ/|(n)|bèo nhún cổ áo", "gigue|/ʒi:g/|(n)|điệu nhảy", "jongleur|/ʒɒŋˈglɜ:/|(n)|người hát rong", "genet|/ˈʒeneɪ/|(n)|tên Genet", "jardiniere|/ʒɑ:dɪnˈjeə/|(n)|chậu hoa", "julienne|/ˌʒu:liˈen/|(n)|thái sợi", "jus|/ʒu:/|(n)|nước xốt", "jalousie|/ˈʒælu:zi:/|(n)|rèm cửa sổ", "jacquard|/ˈʒækɑ:d/|(n)|vải dệt", "ژ(no)|/ʒ/|", "ژ(no)|/ʒ/|"],
            examplesMedial: ["vision|/ˈvɪʒən/|(n)|tầm nhìn", "television|/ˈtelɪˌvɪʒən/|(n)|tivi", "decision|/dɪˈsɪʒən/|(n)|quyết định", "collision|/kəˈlɪʒən/|(n)|va chạm", "division|/dɪˈvɪʒən/|(n)|sự chia rẽ", "revision|/rɪˈvɪʒən/|(n)|sự ôn tập", "provision|/prəˈvɪʒən/|(n)|sự cung cấp", "explosion|/ɪkˈspləʊʒən/|(n)|vụ nổ", "erosion|/ɪˈrəʊʒən/|(n)|sự xói mòn", "illusion|/ɪˈlu:ʒən/|(n)|ảo tưởng", "conclusion|/kənˈklu:ʒən/|(n)|kết luận", "measure|/ˈmeʒər/|(v)|đo lường", "pleasure|/ˈpleʒər/|(n)|niềm vui", "treasure|/ˈtreʒər/|(n)|kho báu", "leisure|/ˈleʒər/|(n)|sự rảnh rỗi"],
            examplesFinal: ["massage|/ˈmæsɑ:ʒ/|(n)|mát xa", "garage|/ˈgærɑ:ʒ/|(n)|ga-ra", "mirage|/mɪˈrɑ:ʒ/|(n)|ảo ảnh", "camouflage|/ˈkæməflɑ:ʒ/|(n)|sự ngụy trang", "barrage|/ˈbærɑ:ʒ/|(n)|hỏa lực", "entourage|/ˈɒntʊrɑ:ʒ/|(n)|đoàn tùy tùng", "montage|/ˈmɒntɑ:ʒ/|(n)|dựng phim", "corsage|/kɔ:ˈsɑ:ʒ/|(n)|hoa cài áo", "espionage|/ˈespiənɑ:ʒ/|(n)|hoạt động gián điệp", "fuselage|/ˈfju:zəlɑ:ʒ/|(n)|thân máy bay", "prestige|/presˈti:ʒ/|(n)|uy tín", "rouge|/ru:ʒ/|(n)|phấn hồng", "beige|/beɪʒ/|(adj)|màu be", "dressage|/ˈdresɑ:ʒ/|(n)|biểu diễn cưỡi ngựa", "sabotage|/ˈsæbətɑ:ʒ/|(n)|phá hoại"]
        },
        { id: "m", phonetic: "m", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["me|/mi:/|(pro)|tôi (tân ngữ)", "my|/maɪ/|(pro)|của tôi", "man|/mæn/|(n)|đàn ông", "make|/meɪk/|(v)|làm", "more|/mɔ:/|(adv)|nhiều hơn", "most|/məʊst/|(adv)|hầu hết", "much|/mʌtʃ/|(adv)|nhiều", "many|/ˈmeni/|(adj)|nhiều", "must|/mʌst/|(v)|phải", "mother|/ˈmʌðər/|(n)|mẹ", "map|/mæp/|(n)|bản đồ", "moon|/mu:n/|(n)|mặt trăng", "meat|/mi:t/|(n)|thịt", "milk|/mɪlk/|(n)|sữa", "money|/ˈmʌni/|(n)|tiền"],
            examplesMedial: ["summer|/ˈsʌmər/|(n)|mùa hè", "family|/ˈfæməli/|(n)|gia đình", "number|/ˈnʌmbər/|(n)|con số", "woman|/ˈwʊmən/|(n)|phụ nữ", "women|/ˈwɪmɪn/|(n)|phụ nữ (số nhiều)", "almost|/ˈɔ:lməʊst/|(adv)|hầu như", "human|/ˈhju:mən/|(n)|con người", "animal|/ˈænɪməl/|(n)|động vật", "common|/ˈkɒmən/|(adj)|phổ biến", "demand|/dɪˈmɑ:nd/|(n)|yêu cầu", "famous|/ˈfeɪməs/|(adj)|nổi tiếng", "promise|/ˈprɒmɪs/|(v)|hứa", "camera|/ˈkæmərə/|(n)|máy ảnh", "remain|/rɪˈmeɪn/|(v)|còn lại", "remember|/rɪˈmembər/|(v)|nhớ"],
            examplesFinal: ["am|/æm/|(v)|là", "time|/taɪm/|(n)|thời gian", "come|/kʌm/|(v)|đến", "some|/sʌm/|(det)|vài", "home|/həʊm/|(n)|nhà", "name|/neɪm/|(n)|tên", "room|/ru:m/|(n)|phòng", "team|/ti:m/|(n)|đội", "form|/fɔ:m/|(n)|hình thức", "farm|/fɑ:m/|(n)|nông trại", "warm|/wɔ:m/|(adj)|ấm áp", "arm|/ɑ:m/|(n)|cánh tay", "game|/geɪm/|(n)|trò chơi", "seem|/si:m/|(v)|dường như", "swim|/swɪm/|(v)|bơi"]
        },
        { id: "n", phonetic: "n", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["no|/nəʊ/|(adv)|không", "not|/nɒt/|(adv)|không", "now|/naʊ/|(adv)|bây giờ", "new|/nju:/|(adj)|mới", "never|/ˈnevər/|(adv)|không bao giờ", "next|/nekst/|(adj)|tiếp theo", "need|/ni:d/|(v)|cần", "name|/neɪm/|(n)|tên", "night|/naɪt/|(n)|ban đêm", "nothing|/ˈnʌθɪŋ/|(pro)|không gì cả", "near|/nɪə/|(prep)|gần", "neck|/nek/|(n)|cổ", "nice|/naɪs/|(adj)|đẹp", "nose|/nəʊz/|(n)|mũi", "nurse|/nɜ:s/|(n)|y tá"],
            examplesMedial: ["any|/ˈeni/|(det)|bất kỳ", "many|/ˈmeni/|(adj)|nhiều", "money|/ˈmʌni/|(n)|tiền", "only|/ˈəʊnli/|(adv)|chỉ", "under|/ˈʌndər/|(prep)|dưới", "animal|/ˈænɪməl/|(n)|động vật", "behind|/bɪˈhaɪnd/|(prep)|phía sau", "finish|/ˈfɪnɪʃ/|(v)|kết thúc", "minute|/ˈmɪnɪt/|(n)|phút", "planet|/ˈplænɪt/|(n)|hành tinh", "tennis|/ˈtenɪs/|(n)|quần vợt", "window|/ˈwɪndəʊ/|(n)|cửa sổ", "winner|/ˈwɪnər/|(n)|người chiến thắng", "journey|/ˈdʒɜ:ni/|(n)|hành trình", "dinner|/ˈdɪnər/|(n)|bữa tối"],
            examplesFinal: ["in|/ɪn/|(prep)|trong", "on|/ɒn/|(prep)|trên", "an|/æn/|(art)|một", "can|/kæn/|(v)|có thể", "man|/mæn/|(n)|đàn ông", "than|/ðæn/|(conj)|hơn", "then|/ðen/|(adv)|sau đó", "when|/wen/|(adv)|khi nào", "ten|/ten/|(n)|mười", "pen|/pen/|(n)|bút", "run|/rʌn/|(v)|chạy", "sun|/sʌn/|(n)|mặt trời", "fun|/fʌn/|(n)|niềm vui", "down|/daʊn/|(adv)|xuống", "town|/taʊn/|(n)|thị trấn"]
        },
        { id: "ng", phonetic: "ŋ", type: "Voiced Consonant", voiced: true, 
            examplesInitial: [],
            examplesMedial: ["singer|/ˈsɪŋər/|(n)|ca sĩ", "hanger|/ˈhæŋər/|(n)|móc áo", "ringer|/ˈrɪŋər/|(n)|người rung chuông", "banger|/ˈbæŋər/|(n)|xúc xích", "doing|/ˈdu:ɪŋ/|(v)|đang làm", "going|/ˈgəʊɪŋ/|(v)|đang đi", "coming|/ˈkʌmɪŋ/|(v)|đang đến", "saying|/ˈseɪɪŋ/|(v)|đang nói", "playing|/ˈpleɪɪŋ/|(v)|đang chơi", "reading|/ˈri:dɪŋ/|(v)|đang đọc", "writing|/ˈraɪtɪŋ/|(v)|đang viết", "working|/ˈwɜ:kɪŋ/|(v)|đang làm việc", "thinking|/ˈθɪŋkɪŋ/|(v)|đang nghĩ", "longing|/ˈlɒŋɪŋ/|(n)|sự khao khát", "belonging|/bɪˈlɒŋɪŋ/|(n)|đồ dùng cá nhân"],
            examplesFinal: ["sing|/sɪŋ/|(v)|hát", "song|/sɒŋ/|(n)|bài hát", "ring|/rɪŋ/|(n)|chiếc nhẫn", "king|/kɪŋ/|(n)|nhà vua", "wing|/wɪŋ/|(n)|cánh", "thing|/θɪŋ/|(n)|đồ vật", "bring|/brɪŋ/|(v)|mang lại", "spring|/sprɪŋ/|(n)|mùa xuân", "string|/strɪŋ/|(n)|sợi dây", "strong|/strɒŋ/|(adj)|mạnh", "long|/lɒŋ/|(adj)|dài", "wrong|/rɒŋ/|(adj)|sai", "bang|/bæŋ/|(n)|tiếng nổ", "hang|/hæŋ/|(v)|treo", "sang|/sæŋ/|(v)|đã hát"]
        },
        { id: "h", phonetic: "h", type: "Unvoiced Consonant", voiced: false, 
            examplesInitial: ["he|/hi:/|(pro)|anh ấy", "him|/hɪm/|(pro)|anh ấy", "his|/hɪz/|(pro)|của anh ấy", "her|/hɜ:/|(pro)|cô ấy", "here|/hɪə/|(adv)|ở đây", "how|/haʊ/|(adv)|như thế nào", "who|/hu:/|(pro)|ai", "have|/hæv/|(v)|có", "had|/hæd/|(v)|đã có", "has|/hæz/|(v)|có (ngôi 3)", "house|/haʊs/|(n)|ngôi nhà", "home|/həʊm/|(n)|tổ ấm", "horse|/hɔ:s/|(n)|con ngựa", "hot|/hɒt/|(adj)|nóng", "hat|/hæt/|(n)|cái mũ"],
            examplesMedial: ["behind|/bɪˈhaɪnd/|(prep)|phía sau", "perhaps|/pəˈhæps/|(adv)|có lẽ", "behave|/bɪˈheɪv/|(v)|cư xử", "somehow|/ˈsʌmhaʊ/|(adv)|bằng cách nào đó", "unhook|/ʌnˈhʊk/|(v)|mở móc", "ahead|/əˈhed/|(adv)|phía trước", "anyhow|/ˈenihaʊ/|(adv)|dù sao đi nữa", "boyhood|/ˈbɔɪhʊd/|(n)|thời niên thiếu", "rehouse|/ri:ˈhaʊz/|(v)|chuyển nhà", "inhale|/ɪnˈheɪl/|(v)|hít vào", "exhale|/eksˈheɪl/|(v)|thở ra", "uphill|/ʌpˈhɪl/|(adv)|lên dốc", "outhouse|/ˈaʊthaʊs/|(n)|nhà phụ", "childhood|/ˈtʃaɪldhʊd/|(n)|tuổi thơ", "falsehood|/ˈfɔ:lshʊd/|(n)|sự giả dối"],
            examplesFinal: []
        },
        { id: "l", phonetic: "l", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["look|/lʊk/|(v)|nhìn", "like|/laɪk/|(v)|thích", "love|/lʌv/|(n)|tình yêu", "live|/lɪv/|(v)|sống", "life|/laɪf/|(n)|cuộc sống", "long|/lɒŋ/|(adj)|dài", "last|/lɑ:st/|(adj)|cuối cùng", "late|/leɪt/|(adj)|muộn", "let|/let/|(v)|để cho", "left|/left/|(adj)|bên trái", "lake|/leɪk/|(n)|hồ", "land|/lænd/|(n)|đất đai", "large|/lɑ:dʒ/|(adj)|rộng lớn", "laugh|/lɑ:f/|(v)|cười", "law|/lɔ:/|(n)|luật pháp"],
            examplesMedial: ["early|/ˈɜ:li/|(adj)|sớm", "only|/ˈəʊnli/|(adv)|chỉ", "really|/ˈrɪəli/|(adv)|thực sự", "family|/ˈfæməli/|(n)|gia đình", "always|/ˈɔ:lweɪz/|(adv)|luôn luôn", "almost|/ˈɔ:lməʊst/|(adv)|hầu như", "also|/ˈɔ:lsəʊ/|(adv)|cũng", "help|/help/|(v)|giúp đỡ", "child|/tʃaɪld/|(n)|đứa trẻ", "cold|/kəʊld/|(adj)|lạnh", "color|/ˈkʌlər/|(n)|màu sắc", "daily|/ˈdeɪli/|(adj)|hàng ngày", "dollar|/ˈdɒlər/|(n)|đô la", "police|/pəˈli:s/|(n)|cảnh sát", "yellow|/ˈjeləʊ/|(adj)|màu vàng"],
            examplesFinal: ["all|/ɔ:l/|(pro)|tất cả", "call|/kɔ:l/|(v)|gọi", "fall|/fɔ:l/|(v)|rơi", "tall|/tɔ:l/|(adj)|cao", "small|/smɔ:l/|(adj)|nhỏ", "well|/wel/|(adv)|tốt", "tell|/tel/|(v)|kể", "sell|/sel/|(v)|bán", "feel|/fi:l/|(v)|cảm thấy", "real|/rɪəl/|(adj)|thực", "school|/sku:l/|(n)|trường học", "girl|/gɜ:l/|(n)|cô gái", "world|/wɜ:ld/|(n)|thế giới", "child(final is ld)|/tʃaɪld/|(n)|đứa trẻ", "old|/əʊld/|(adj)|cũ, già"]
        },
        { id: "r", phonetic: "r", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["right|/raɪt/|(adj)|đúng, phải", "read|/ri:d/|(v)|đọc", "red|/red/|(adj)|màu đỏ", "run|/rʌn/|(v)|chạy", "room|/ru:m/|(n)|phòng", "road|/rəʊd/|(n)|con đường", "rock|/rɒk/|(n)|đá", "rule|/ru:l/|(n)|luật", "rest|/rest/|(n)|sự nghỉ ngơi", "real|/rɪəl/|(adj)|thực tế", "rain|/reɪn/|(n)|mưa", "rat|/ræt/|(n)|con chuột", "reach|/ri:tʃ/|(v)|chạm tới", "rich|/rɪtʃ/|(adj)|giàu có", "ride|/raɪd/|(v)|cưỡi, lái"],
            examplesMedial: ["very|/ˈveri/|(adv)|rất", "sorry|/ˈsɒri/|(adj)|xin lỗi", "carry|/ˈkæri/|(v)|mang, vác", "marry|/ˈmæri/|(v)|kết hôn", "hurry|/ˈhʌri/|(v)|vội vã", "around|/əˈraʊnd/|(prep)|xung quanh", "parent|/ˈpeərənt/|(n)|cha mẹ", "story|/ˈstɔ:ri/|(n)|câu chuyện", "history|/ˈhɪstəri/|(n)|lịch sử", "camera|/ˈkæmərə/|(n)|máy ảnh", "mirror|/ˈmɪrər/|(n)|gương", "arrow|/ˈærəʊ/|(n)|mũi tên", "error|/ˈerər/|(n)|lỗi", "narrow|/ˈnærəʊ/|(adj)|hẹp", "terror|/ˈterər/|(n)|sự kinh hoàng"],
            examplesFinal: ["car|/kɑ:/|(n)|xe hơi", "far|/fɑ:/|(adj)|xa", "star|/stɑ:/|(n)|ngôi sao", "bar|/bɑ:/|(n)|quầy bar", "jar|/dʒɑ:/|(n)|cái lọ", "door|/dɔ:/|(n)|cánh cửa", "floor|/flɔ:/|(n)|sàn nhà", "four|/fɔ:/|(n)|số bốn", "pour|/pɔ:/|(v)|rót", "hair|/heə/|(n)|tóc", "chair|/tʃeə/|(n)|ghế", "bear|/beə/|(n)|con gấu", "pear|/peə/|(n)|quả lê", "wear|/weə/|(v)|mặc", "swear|/sweə/|(v)|thề"]
        },
        { id: "w", phonetic: "w", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["we|/wi:/|(pro)|chúng tôi", "way|/weɪ/|(n)|đường, cách", "well|/wel/|(adv)|tốt", "want|/wɒnt/|(v)|muốn", "what|/wɒt/|(pro)|cái gì", "when|/wen/|(adv)|khi nào", "where|/weə/|(adv)|ở đâu", "why|/waɪ/|(adv)|tại sao", "which|/wɪtʃ/|(pro)|cái nào", "with|/wɪð/|(prep)|với", "water|/ˈwɔ:tər/|(n)|nước", "woman|/ˈwʊmən/|(n)|phụ nữ", "women|/ˈwɪmɪn/|(n)|phụ nữ (số nhiều)", "word|/wɜ:d/|(n)|từ vựng", "work|/wɜ:k/|(v)|làm việc"],
            examplesMedial: ["away|/əˈweɪ/|(adv)|xa", "always|/ˈɔ:lweɪz/|(adv)|luôn luôn", "between|/bɪˈtwi:n/|(prep)|giữa", "someone|/ˈsʌmwʌn/|(pro)|ai đó", "anyone|/ˈeniwʌn/|(pro)|bất cứ ai", "everyone|/ˈevriwʌn/|(pro)|mọi người", "forward|/ˈfɔ:wəd/|(adv)|về phía trước", "backward|/ˈbækwəd/|(adv)|về phía sau", "reward|/rɪˈwɔ:d/|(n)|phần thưởng", "awake|/əˈweɪk/|(adj)|thức giấc", "await|/əˈweɪt/|(v)|chờ đợi", "nowhere|/ˈnəʊweə/|(adv)|không nơi nào", "everywhere|/ˈevriweə/|(adv)|mọi nơi", "anyway|/ˈeniweɪ/|(adv)|dù sao", "somewhat|/ˈsʌmwɒt/|(adv)|hơi hơi"],
            examplesFinal: []
        },
        { id: "y", phonetic: "j", type: "Voiced Consonant", voiced: true, 
            examplesInitial: ["you|/ju:/|(pro)|bạn", "your|/jɔ:/|(pro)|của bạn", "yes|/jes/|(adv)|vâng", "yet|/jet/|(adv)|chưa", "year|/jɪə/|(n)|năm", "young|/jʌŋ/|(adj)|trẻ", "yellow|/ˈjeləʊ/|(adj)|màu vàng", "yesterday|/ˈjestədeɪ/|(n)|hôm qua", "yell|/jel/|(v)|hét lên", "yard|/jɑ:d/|(n)|cái sân", "yam|/jæm/|(n)|khoai lang", "yawn|/jɔ:n/|(v)|ngáp", "yeast|/ji:st/|(n)|men nở", "yield|/ji:ld/|(v)|năng suất, nhường", "yoga|/ˈjəʊgə/|(n)|yoga"],
            examplesMedial: ["beyond|/bɪˈjɒnd/|(prep)|vượt ra ngoài", "million|/ˈmɪljən/|(n)|triệu", "onion|/ˈʌnjən/|(n)|củ hành", "opinion|/əˈpɪnjən/|(n)|ý kiến", "behavior|/bɪˈheɪvjər/|(n)|hành vi", "reunion|/ri:ˈju:niən/|(n)|cuộc đoàn tụ", "familiar|/fəˈmɪliər/|(adj)|quen thuộc", "peculiar|/pɪˈkju:liər/|(adj)|kỳ lạ", "senior|/ˈsi:niər/|(n)|người lớn tuổi hơn", "junior|/ˈdʒu:niər/|(n)|người nhỏ tuổi hơn", "companion|/kəmˈpæniən/|(n)|bạn đồng hành", "canyon|/ˈkænjən/|(n)|hẻm núi", "royal|/ˈrɔɪəl/|(adj)|hoàng gia", "loyal|/ˈlɔɪəl/|(adj)|trung thành", "lawyer|/ˈlɔɪər/|(n)|luật sư"],
            examplesFinal: []
        }
    ],
    clusters: [
        { id: "st", phonetic: "st", type: "Consonant Cluster", voiced: false, 
            examplesInitial: ["stop|/stɒp/|(v)|dừng lại", "start|/stɑ:t/|(v)|bắt đầu", "stay|/steɪ/|(v)|ở lại", "student|/ˈstu:dənt/|(n)|học sinh", "study|/ˈstʌdi/|(v)|học", "stand|/stænd/|(v)|đứng", "star|/stɑ:/|(n)|ngôi sao", "store|/stɔ:/|(n)|cửa hàng", "step|/step/|(n)|bước đi", "story|/ˈstɔ:ri/|(n)|câu chuyện", "station|/ˈsteɪʃən/|(n)|nhà ga", "state|/steɪt/|(n)|tiểu bang", "staff|/stɑ:f/|(n)|nhân viên", "stage|/steɪdʒ/|(n)|sân khấu", "stairs|/steəz/|(n)|cầu thang"],
            examplesMedial: ["history|/ˈhɪstəri/|(n)|lịch sử", "sister|/ˈsɪstər/|(n)|chị/em gái", "master|/ˈmɑ:stər/|(n)|bậc thầy", "custom|/ˈkʌstəm/|(n)|phong tục", "instance|/ˈɪnstəns/|(n)|ví dụ", "system|/ˈsɪstəm/|(n)|hệ thống", "plastic|/ˈplæstɪk/|(n)|nhựa", "distance|/ˈdɪstəns/|(n)|khoảng cách", "mister|/ˈmɪstər/|(n)|quý ngài", "postal|/ˈpəʊstəl/|(adj)|thuộc bưu điện", "eastern|/ˈi:stən/|(adj)|thuộc phương Đông", "western|/ˈwestən/|(adj)|thuộc phương Tây", "restore|/rɪˈstɔ:/|(v)|phục hồi", "destroy|/dɪˈstrɔɪ/|(v)|phá hủy", "mistake|/mɪˈsteɪk/|(n)|lỗi lầm"],
            examplesFinal: ["last|/lɑ:st/|(adj)|cuối cùng", "fast|/fɑ:st/|(adj)|nhanh", "past|/pɑ:st/|(n)|quá khứ", "lost|/lɒst/|(adj)|bị mất", "just|/dʒʌst/|(adv)|chỉ", "test|/test/|(n)|kiểm tra", "best|/best/|(adj)|tốt nhất", "rest|/rest/|(n)|nghỉ ngơi", "west|/west/|(n)|hướng tây", "cost|/kɒst/|(n)|chi phí", "toast|/təʊst/|(n)|bánh mì nướng", "boost|/bu:st/|(v)|tăng cường", "ghost|/gəʊst/|(n)|con ma", "host|/həʊst/|(n)|chủ nhà", "post|/pəʊst/|(n)|bài viết"]
        },
        { id: "gz", phonetic: "gz", type: "Consonant Cluster", voiced: true, 
            examplesInitial: [],
            examplesMedial: ["exact|/ɪgˈzækt/|(adj)|chính xác", "example|/ɪgˈzɑ:mpəl/|(n)|ví dụ", "exist|/ɪgˈzɪst/|(v)|tồn tại", "exam|/ɪgˈzæm/|(n)|bài thi", "exit|/ˈegzɪt/|(n)|lối ra", "exhaust|/ɪgˈzɔ:st/|(v)|làm kiệt sức", "exhibit|/ɪgˈzɪbɪt/|(v)|trưng bày", "executive|/ɪgˈzekjətɪv/|(n)|người điều hành", "exotic|/ɪgˈzɒtɪk/|(adj)|kỳ lạ", "examine|/ɪgˈzæmɪn/|(v)|kiểm tra", "exempt|/ɪgˈzempt/|(adj)|được miễn", "exaggerate|/ɪgˈzædʒəreɪt/|(v)|phóng đại", "exult|/ɪgˈzʌlt/|(v)|vui mừng", "exert|/ɪgˈzɜ:t/|(v)|dùng sức", "auxiliary|/ɔ:gˈzɪliəri/|(adj)|phụ trợ"],
            examplesFinal: ["eggs|/egz/|(n)|những quả trứng", "bugs|/bʌgz/|(n)|những con bọ", "bags|/bægz/|(n)|những cái túi", "dogs|/dɒgz/|(n)|những con chó", "logs|/lɒgz/|(n)|những khúc gỗ", "pigs|/pɪgz/|(n)|những con lợn", "frogs|/frɒgz/|(n)|những con ếch", "rugs|/rʌgz/|(n)|những tấm thảm", "mugs|/mʌgz/|(n)|những cái cốc", "hugs|/hʌgz/|(n)|những cái ôm", "flags|/flægz/|(n)|những lá cờ", "plugs|/plʌgz/|(n)|những phích cắm", "tags|/tægz/|(n)|những cái thẻ", "rags|/rægz/|(n)|những mảnh giẻ", "wigs|/wɪgz/|(n)|những bộ tóc giả"]
        },
        { id: "ks", phonetic: "ks", type: "Consonant Cluster", voiced: false, 
            examplesInitial: [],
            examplesMedial: ["taxi|/ˈtæksi/|(n)|xe taxi", "oxygen|/ˈɒksɪdʒən/|(n)|khí oxy", "mixture|/ˈmɪkstʃər/|(n)|hỗn hợp", "texture|/ˈtekstʃər/|(n)|kết cấu", "proxy|/ˈprɒksi/|(n)|người đại diện", "toxic|/ˈtɒksɪk/|(adj)|độc hại", "excel|/ɪkˈsel/|(v)|xuất sắc", "pixel|/ˈpɪksəl/|(n)|điểm ảnh", "boxing|/ˈbɒksɪŋ/|(n)|quyền anh", "fixing|/ˈfɪksɪŋ/|(v)|đang sửa", "mixing|/ˈmɪksɪŋ/|(v)|đang trộn", "axle|/ˈæksəl/|(n)|trục bánh xe", "maxim|/ˈmæksɪm/|(n)|châm ngôn", "galaxy|/ˈgæləksi/|(n)|thiên hà", "accident|/ˈæksɪdənt/|(n)|tai nạn"],
            examplesFinal: ["six|/sɪks/|(n)|số sáu", "box|/bɒks/|(n)|cái hộp", "fox|/fɒks/|(n)|con cáo", "next|/nekst/|(adj)|tiếp theo", "text|/tekst/|(n)|văn bản", "mix|/mɪks/|(v)|trộn", "fix|/fɪks/|(v)|sửa chữa", "relax|/rɪˈlæks/|(v)|thư giãn", "tax|/tæks/|(n)|thuế", "wax|/wæks/|(n)|sáp", "max|/mæks/|(n)|tối đa", "flex|/fleks/|(v)|uốn cong", "axe|/æks/|(n)|cái rìu", "ox|/ɒks/|(n)|con bò đực", "socks|/sɒks/|(n)|đôi tất"]
        },
        { id: "tr", phonetic: "tr", type: "Consonant Cluster", voiced: false, 
            examplesInitial: ["tree|/tri:/|(n)|cái cây", "try|/traɪ/|(v)|thử, cố", "train|/treɪn/|(n)|chuyến tàu", "true|/tru:/|(adj)|đúng", "travel|/ˈtrævəl/|(v)|du lịch", "trust|/trʌst/|(v)|tin tưởng", "trip|/trɪp/|(n)|chuyến đi", "treat|/tri:t/|(v)|đối xử", "trick|/trɪk/|(n)|thủ thuật", "track|/træk/|(n)|dấu vết", "traffic|/ˈtræfɪk/|(n)|giao thông", "trouble|/ˈtrʌbəl/|(n)|rắc rối", "trade|/treɪd/|(n)|thương mại", "truck|/trʌk/|(n)|xe tải", "trash|/træʃ/|(n)|rác"],
            examplesMedial: ["country|/ˈkʌntri/|(n)|đất nước", "control|/kənˈtrəʊl/|(v)|kiểm soát", "central|/ˈsentrəl/|(adj)|trung tâm", "entrance|/ˈentrəns/|(n)|lối vào", "metric|/ˈmetrɪk/|(adj)|hệ mét", "electric|/ɪˈlektrɪk/|(adj)|thuộc về điện", "mattress|/ˈmætrəs/|(n)|cái nệm", "patrol|/pəˈtrəʊl/|(v)|tuần tra", "petrol|/ˈpetrəl/|(n)|xăng", "hatred|/ˈheɪtrɪd/|(n)|sự căm ghét", "betray|/bɪˈtreɪ/|(v)|phản bội", "retreat|/rɪˈtri:t/|(v)|rút lui", "poetry|/ˈpəʊɪtri/|(n)|thơ ca", "poultry|/ˈpəʊltri/|(n)|gia cầm", "portray|/pɔ:ˈtreɪ/|(v)|khắc họa"],
            examplesFinal: []
        },
        { id: "dr", phonetic: "dr", type: "Consonant Cluster", voiced: true, 
            examplesInitial: ["drink|/drɪŋk/|(v)|uống", "drive|/draɪv/|(v)|lái xe", "drop|/drɒp/|(v)|làm rơi", "dry|/draɪ/|(adj)|khô", "draw|/drɔ:/|(v)|vẽ", "dream|/dri:m/|(n)|giấc mơ", "dress|/dres/|(n)|chiếc váy", "drug|/drʌg/|(n)|thuốc", "drum|/drʌm/|(n)|cái trống", "drag|/dræg/|(v)|kéo lê", "drama|/ˈdrɑ:mə/|(n)|kịch bản", "drill|/drɪl/|(n)|máy khoan", "drown|/draʊn/|(v)|chết đuối", "dragon|/ˈdrægən/|(n)|con rồng", "driver|/ˈdraɪvər/|(n)|tài xế"],
            examplesMedial: ["hundred|/ˈhʌndrəd/|(n)|trăm", "children|/ˈtʃɪldrən/|(n)|những đứa trẻ", "address|/əˈdres/|(n)|địa chỉ", "bedroom|/ˈbedru:m/|(n)|phòng ngủ", "wardrobe|/ˈwɔ:drəʊb/|(n)|tủ quần áo", "laundry|/ˈlɔ:ndri/|(n)|tiệm giặt là", "hydra|/ˈhaɪdrə/|(n)|rắn chín đầu", "syndrome|/ˈsɪndrəʊm/|(n)|hội chứng", "hydrant|/ˈhaɪdrənt/|(n)|trụ nước", "Madrid|/məˈdrɪd/|(n)|thành phố Madrid", "withdraw|/wɪðˈdrɔ:/|(v)|rút khỏi", "cathedral|/kəˈθi:drəl/|(n)|nhà thờ lớn", "squadron|/ˈskwɒdrən/|(n)|phi đội", "hatred|/ˈheɪtrɪd/|(n)|lòng hận thù", "dandruff|/ˈdændrʌf/|(n)|gàu"],
            examplesFinal: []
        },
        { id: "pl", phonetic: "pl", type: "Consonant Cluster", voiced: false, 
            examplesInitial: ["play|/pleɪ/|(v)|chơi", "please|/pli:z/|(adv)|vui lòng", "place|/pleɪs/|(n)|địa điểm", "plan|/plæn/|(n)|kế hoạch", "plant|/plɑ:nt/|(n)|thực vật", "plain|/pleɪn/|(adj)|trơn, giản dị", "plane|/pleɪn/|(n)|máy bay", "plastic|/ˈplæstɪk/|(n)|nhựa", "plate|/pleɪt/|(n)|cái đĩa", "plus|/plʌs/|(prep)|cộng", "plug|/plʌg/|(n)|phích cắm", "plum|/plʌm/|(n)|quả mận", "plenty|/ˈplenti/|(pro)|nhiều", "planet|/ˈplænɪt/|(n)|hành tinh", "plot|/plɒt/|(n)|cốt truyện"],
            examplesMedial: ["apply|/əˈplaɪ/|(v)|áp dụng", "reply|/rɪˈplaɪ/|(v)|phản hồi", "supply|/səˈplaɪ/|(v)|cung cấp", "employ|/ɪmˈplɔɪ/|(v)|thuê mướn", "complain|/kəmˈpleɪn/|(v)|phàn nàn", "complete|/kəmˈpli:t/|(adj)|hoàn thành", "display|/dɪˈspleɪ/|(v)|trưng bày", "replace|/rɪˈpleɪs/|(v)|thay thế", "explain|/ɪkˈspleɪn/|(v)|giải thích", "deeply|/ˈdi:pli/|(adv)|sâu sắc", "duplicate|/ˈdju:plɪkeɪt/|(v)|nhân bản", "complex|/ˈkɒmpleks/|(adj)|phức tạp", "imply|/ɪmˈplaɪ/|(v)|ngụ ý", "explore|/ɪkˈsplɔ:/|(v)|khám phá", "explode|/ɪkˈspləʊd/|(v)|phát nổ"],
            examplesFinal: []
        },
        { id: "br", phonetic: "br", type: "Consonant Cluster", voiced: true, 
            examplesInitial: ["bring|/brɪŋ/|(v)|mang lại", "brother|/ˈbrʌðər/|(n)|anh em trai", "brown|/braʊn/|(adj)|màu nâu", "break|/breɪk/|(v)|làm gãy", "bread|/bred/|(n)|bánh mì", "bridge|/brɪdʒ/|(n)|cây cầu", "bright|/braɪt/|(adj)|sáng sủa", "brain|/breɪn/|(n)|bộ não", "branch|/brɑ:ntʃ/|(n)|nhánh", "brave|/breɪv/|(adj)|dũng cảm", "brush|/brʌʃ/|(n)|bàn chải", "breath|/breθ/|(n)|hơi thở", "brick|/brɪk/|(n)|viên gạch", "broad|/brɔ:d/|(adj)|rộng", "brief|/bri:f/|(adj)|ngắn gọn"],
            examplesMedial: ["library|/ˈlaɪbrəri/|(n)|thư viện", "celebrate|/ˈselɪbreɪt/|(v)|kỷ niệm", "fabric|/ˈfæbrɪk/|(n)|vải vóc", "zebra|/ˈzebrə/|(n)|ngựa vằn", "cobra|/ˈkəʊbrə/|(n)|rắn hổ mang", "algebra|/ˈældʒɪbrə/|(n)|đại số", "vibrate|/vaɪˈbreɪt/|(v)|rung động", "eyebrow|/ˈaɪbraʊ/|(n)|lông mày", "hybrid|/ˈhaɪbrɪd/|(adj)|lai", "umbrella|/ʌmˈbrelə/|(n)|cái ô", "subtract|/səbˈtrækt/|(v)|trừ", "embrace|/ɪmˈbreɪs/|(v)|ôm ấp", "embryo|/ˈembriəʊ/|(n)|phôi thai", "abbreviate|/əˈbri:vieɪt/|(v)|viết tắt", "abrupt|/əˈbrʌpt/|(adj)|đột ngột"],
            examplesFinal: []
        },
        { id: "gr", phonetic: "gr", type: "Consonant Cluster", voiced: true, 
            examplesInitial: ["great|/greɪt/|(adj)|tuyệt vời", "green|/gri:n/|(adj)|màu xanh lá", "group|/gru:p/|(n)|nhóm", "grow|/grəʊ/|(v)|lớn lên", "ground|/graʊnd/|(n)|mặt đất", "grab|/græb/|(v)|vồ lấy", "grand|/grænd/|(adj)|hoành tráng", "grass|/grɑ:s/|(n)|cỏ", "grey|/greɪ/|(adj)|màu xám", "gross|/grəʊs/|(adj)|tổng cộng", "grammar|/ˈgræmər/|(n)|ngữ pháp", "grade|/greɪd/|(n)|điểm số", "grape|/greɪp/|(n)|quả nho", "graph|/grɑ:f/|(n)|biểu đồ", "grocery|/ˈgrəʊsəri/|(n)|cửa hàng tạp hóa"],
            examplesMedial: ["angry|/ˈæŋgri/|(adj)|tức giận", "hungry|/ˈhʌŋgri/|(adj)|đói", "agree|/əˈgri:/|(v)|đồng ý", "degree|/dɪˈgri:/|(n)|bằng cấp", "program|/ˈprəʊgræm/|(n)|chương trình", "progress|/ˈprəʊgres/|(n)|sự tiến bộ", "regret|/rɪˈgret/|(v)|hối tiếc", "diagram|/ˈdaɪəgræm/|(n)|sơ đồ", "telegram|/ˈtelɪgræm/|(n)|bức điện tín", "aggressive|/əˈgresɪv/|(adj)|hung hăng", "agriculture|/ˈægrɪkʌltʃər/|(n)|nông nghiệp", "biography|/baɪˈɒgrəfi/|(n)|tiểu sử", "geography|/dʒiˈɒgrəfi/|(n)|địa lý", "migrant|/ˈmaɪgrənt/|(n)|người di cư", "photograph|/ˈfəʊtəgrɑ:f/|(n)|bức ảnh"],
            examplesFinal: []
        },
        { id: "fl", phonetic: "fl", type: "Consonant Cluster", voiced: false, 
            examplesInitial: ["fly|/flaɪ/|(v)|bay", "flower|/ˈflaʊər/|(n)|hoa", "floor|/flɔ:/|(n)|sàn nhà", "flat|/flæt/|(adj)|phẳng", "flag|/flæg/|(n)|lá cờ", "flame|/fleɪm/|(n)|ngọn lửa", "flash|/flæʃ/|(n)|tia chớp", "fleet|/fli:t/|(n)|hạm đội", "flight|/flaɪt/|(n)|chuyến bay", "float|/fləʊt/|(v)|nổi", "flood|/flʌd/|(n)|lũ lụt", "flow|/fləʊ/|(v)|chảy", "fluid|/ˈflu:ɪd/|(n)|chất lỏng", "flute|/flu:t/|(n)|ống sáo", "flavor|/ˈfleɪvər/|(n)|hương vị"],
            examplesMedial: ["reflect|/rɪˈflekt/|(v)|phản chiếu", "deflect|/dɪˈflekt/|(v)|làm chệch hướng", "conflict|/ˈkɒnflɪkt/|(n)|xung đột", "inflict|/ɪnˈflɪkt/|(v)|gây ra", "influence|/ˈɪnfluəns/|(n)|ảnh hưởng", "sunflower|/ˈsʌnflaʊər/|(n)|hoa hướng dương", "snowflake|/ˈsnəʊfleɪk/|(n)|bông tuyết", "baffling|/ˈbæflɪŋ/|(adj)|khó hiểu", "rifleman|/ˈraɪflmən/|(n)|lính súng trường", "reflex|/ˈri:fleks/|(n)|phản xạ", "butterfly|/ˈbʌtəflaɪ/|(n)|con bướm", "influx|/ˈɪnflʌks/|(n)|dòng chảy vào", "leaflet|/ˈli:flɪt/|(n)|tờ rơi", "souffle|/ˈsu:fleɪ/|(n)|bánh xốp", "afflict|/əˈflɪkt/|(v)|làm đau khổ"],
            examplesFinal: []
        },
        { id: "sl", phonetic: "sl", type: "Consonant Cluster", voiced: false, 
            examplesInitial: ["sleep|/sli:p/|(v)|ngủ", "slow|/sləʊ/|(adj)|chậm", "slice|/slaɪs/|(n)|lát cắt", "slide|/slaɪd/|(v)|trượt", "slip|/slɪp/|(v)|trượt chân", "slightly|/ˈslaɪtli/|(adv)|hơi hơi", "slim|/slɪm/|(adj)|mảnh khảnh", "slam|/slæm/|(v)|đóng sầm", "slap|/slæp/|(v)|tát", "slave|/sleɪv/|(n)|nô lệ", "sleeve|/sli:v/|(n)|tay áo", "slender|/ˈslendər/|(adj)|thon thả", "slope|/sləʊp/|(n)|độ dốc", "slot|/slɒt/|(n)|khe cắm", "sleet|/sli:t/|(n)|mưa tuyết"],
            examplesMedial: ["asleep|/əˈsli:p/|(adj)|đang ngủ", "slowly|/ˈsləʊli/|(adv)|chậm rãi", "translate|/trænzˈleɪt/|(v)|dịch", "mislead|/mɪsˈli:d/|(v)|làm lạc hướng", "dislike|/dɪsˈlaɪk/|(v)|không thích", "bracelet|/ˈbreɪslɪt/|(n)|vòng tay", "landslide|/ˈlændslaɪd/|(n)|lở đất", "coleslaw|/ˈkəʊlslɔ:/|(n)|salad bắp cải", "enslave|/ɪnˈsleɪv/|(v)|bắt làm nô lệ", "slipknot|/ˈslɪpnɒt/|(n)|nút thòng lọng", "mudslide|/ˈmʌdslaɪd/|(n)|lũ bùn", "snowslide|/ˈsnəʊslaɪd/|(n)|tuyết lở", "measles|/ˈmi:zəlz/|(n)|bệnh sởi", "restless|/ˈrestləs/|(adj)|bồn chồn", "sleeveless|/ˈsli:vləs/|(adj)|không tay áo"],
            examplesFinal: []
        },
        { id: "sm", phonetic: "sm", type: "Consonant Cluster", voiced: false, 
            examplesInitial: ["small|/smɔ:l/|(adj)|nhỏ", "smile|/smaɪl/|(v)|mỉm cười", "smoke|/sməʊk/|(v)|hút thuốc", "smell|/smel/|(v)|ngửi", "smart|/smɑ:t/|(adj)|thông minh", "smash|/smæʃ/|(v)|đập vỡ", "smooth|/smu:ð/|(adj)|mượt mà", "smear|/smɪə/|(v)|bôi trét", "smog|/smɒg/|(n)|khói bụi", "smite|/smaɪt/|(v)|đập", "smith|/smɪθ/|(n)|thợ rèn", "smug|/smʌg/|(adj)|tự mãn", "smuggle|/ˈsmʌgəl/|(v)|buôn lậu", "smirk|/smɜ:k/|(v)|cười tự mãn", "smoothie|/ˈsmu:ði/|(n)|sinh tố"],
            examplesMedial: ["cosmic|/ˈkɒzmɪk/|(adj)|thuộc vũ trụ", "plasma|/ˈplæzmə/|(n)|huyết tương", "dismiss|/dɪsˈmɪs/|(v)|sa thải", "charisma|/kəˈrɪzmə/|(n)|sức hút", "transmit|/trænzˈmɪt/|(v)|truyền phát", "dismal|/ˈdɪzməl/|(adj)|buồn thảm", "asthma|/ˈæsmə/|(n)|bệnh hen suyễn", "pacemaker|/ˈpeɪsmeɪkər/|(n)|máy tạo nhịp", "bismuth|/ˈbɪzməθ/|(n)|nguyên tố bitmut", "jasmine|/ˈdʒæzmɪn/|(n)|hoa nhài", "osmosis|/ɒzˈməʊsɪs/|(n)|sự thẩm thấu", "seismic|/ˈsaɪzmɪk/|(adj)|thuộc địa chấn", "talisman|/ˈtælɪzmən/|(n)|bùa hộ mệnh", "prism|/ˈprɪzəm/|(n)|lăng kính", "enthusiasm|/ɪnˈθju:ziæzəm/|(n)|sự nhiệt tình"],
            examplesFinal: []
        },
        { id: "sn", phonetic: "sn", type: "Consonant Cluster", voiced: false, 
            examplesInitial: ["snake|/sneɪk/|(n)|con rắn", "snow|/snəʊ/|(n)|tuyết", "snack|/snæk/|(n)|đồ ăn nhẹ", "snap|/snæp/|(v)|bẻ gãy", "sneak|/sni:k/|(v)|lẻn", "sneeze|/sni:z/|(v)|hắt hơi", "sniff|/snɪf/|(v)|khịt mũi", "snob|/snɒb/|(n)|kẻ hợm hĩnh", "snore|/snɔ:/|(v)|ngáy", "snout|/snaʊt/|(n)|mõm", "snub|/snʌb/|(v)|hắt hủi", "snug|/snʌg/|(adj)|ấm cúng", "snail|/sneɪl/|(n)|con ốc sên", "snooker|/ˈsnu:kər/|(n)|bi-da", "snoop|/snu:p/|(v)|rình mò"],
            examplesMedial: ["parsnip|/ˈpɑ:snɪp/|(n)|củ cải vàng", "disney|/ˈdɪzni/|(n)|hãng Disney", "grossness|/ˈgrəʊsnəs/|(n)|sự gớm ghiếc", "looseness|/ˈlu:snəs/|(n)|sự lỏng lẻo", "closeness|/ˈkləʊsnəs/|(n)|sự gần gũi", "crossness|/ˈkrɒsnəs/|(n)|sự cáu kỉnh", "sickness|/ˈsɪknəs/|(n)|bệnh tật", "personal|/ˈpɜ:sənəl/|(adj)|cá nhân", "fascinate|/ˈfæsɪneɪt/|(v)|cuốn hút", "listener|/ˈlɪsənər/|(n)|người nghe", "poisoner|/ˈpɔɪzənər/|(n)|kẻ đầu độc", "fastener|/ˈfɑ:sənər/|(n)|cái móc cài", "sweetener|/ˈswi:tənər/|(n)|chất làm ngọt", "loosener|/ˈlu:sənər/|(n)|cái làm nới lỏng", "christen|/ˈkrɪsən/|(v)|đặt tên thánh"],
            examplesFinal: []
        },
        { id: "sp", phonetic: "sp", type: "Consonant Cluster", voiced: false, 
            examplesInitial: ["speak|/spi:k/|(v)|nói", "sport|/spɔ:t/|(n)|thể thao", "spoon|/spu:n/|(n)|cái thìa", "space|/speɪs/|(n)|không gian", "speed|/spi:d/|(n)|tốc độ", "spell|/spel/|(v)|đánh vần", "spend|/spend/|(v)|dành ra, tiêu", "spill|/spɪl/|(v)|làm đổ", "spin|/spɪn/|(v)|quay", "split|/splɪt/|(v)|chia rẽ", "spoil|/spɔɪl/|(v)|làm hỏng", "sponge|/spʌndʒ/|(n)|miếng bọt biển", "spot|/spɒt/|(n)|điểm", "spray|/spreɪ/|(v)|phun", "spring|/sprɪŋ/|(n)|mùa xuân"],
            examplesMedial: ["whisper|/ˈwɪspər/|(v)|thì thầm", "hospital|/ˈhɒspɪtəl/|(n)|bệnh viện", "respect|/rɪˈspekt/|(n)|sự tôn trọng", "respond|/rɪˈspɒnd/|(v)|phản hồi", "despite|/dɪˈspaɪt/|(prep)|mặc dù", "inspect|/ɪnˈspekt/|(v)|kiểm tra", "prospect|/ˈprɒspekt/|(n)|triển vọng", "suspect|/səˈspekt/|(v)|nghi ngờ", "aspect|/ˈæspekt/|(n)|khía cạnh", "despair|/dɪˈspeə/|(n)|sự tuyệt vọng", "display|/dɪˈspleɪ/|(v)|trưng bày", "dispute|/dɪˈspju:t/|(n)|tranh chấp", "prosper|/ˈprɒspər/|(v)|thịnh vượng", "dispatch|/dɪˈspætʃ/|(v)|gửi đi", "suspend|/səˈspend/|(v)|đình chỉ"],
            examplesFinal: ["wasp|/wɒsp/|(n)|ong bắp cày", "gasp|/gɑ:sp/|(v)|thở hổn hển", "grasp|/grɑ:sp/|(v)|nắm bắt", "clasp|/klɑ:sp/|(n)|cái móc gài", "crisp|/krɪsp/|(adj)|giòn", "lisp|/lɪsp/|(n)|tật nói ngọng", "wisp|/wɪsp/|(n)|nhúm nhỏ", "rasp|/rɑ:sp/|(v)|nói khàn khàn", "hasp|/hæsp/|(n)|cái chốt cửa", "cusp|/kʌsp/|(n)|điểm giao", "clasp|/klɑ:sp/|(v)|ôm chặt", "grasp|/grɑ:sp/|(n)|sự hiểu thấu", "gasp|/gɑ:sp/|(n)|sự ngạc nhiên", "wasp|/wɒsp/|(n)|kẻ hay cáu gắt", "crisp|/krɪsp/|(n)|khoai tây chiên giòn"]
        },
        { id: "sk", phonetic: "sk", type: "Consonant Cluster", voiced: false, 
            examplesInitial: ["school|/sku:l/|(n)|trường học", "skill|/skɪl/|(n)|kỹ năng", "ask(in dialects)|/ɑ:sk/|(v)|hỏi", "sky|/skaɪ/|(n)|bầu trời", "skin|/skɪn/|(n)|da", "skirt|/skɜ:t/|(n)|váy", "desk|/desk/|(n)|bàn làm việc", "task|/tɑ:sk/|(n)|nhiệm vụ", "mask|/mɑ:sk/|(n)|mặt nạ", "risk|/rɪsk/|(n)|rủi ro", "score|/skɔ:/|(n)|điểm số", "screen|/skri:n/|(n)|màn hình", "screw|/skru:/|(n)|đinh ốc", "script|/skrɪpt/|(n)|kịch bản", "scale|/skeɪl/|(n)|cái cân"],
            examplesMedial: ["basket|/ˈbɑ:skɪt/|(n)|cái rổ", "biscuit|/ˈbɪskɪt/|(n)|bánh quy", "escape|/ɪˈskeɪp/|(v)|trốn thoát", "describe|/dɪˈskraɪb/|(v)|miêu tả", "discover|/dɪˈskʌvər/|(v)|khám phá", "discuss|/dɪˈskʌs/|(v)|thảo luận", "rescue|/ˈreskju:/|(v)|giải cứu", "mascot|/ˈmæskɒt/|(n)|linh vật", "cascade|/kæsˈkeɪd/|(n)|thác nước nhỏ", "obscure|/əbˈskjʊə/|(adj)|mờ nhạt", "whisky|/ˈwɪski/|(n)|rượu whisky", "muscular|/ˈmʌskjʊlər/|(adj)|vạm vỡ", "mosquito|/mɒˈski:təʊ/|(n)|con muỗi", "escalate|/ˈeskəleɪt/|(v)|leo thang", "basketry|/ˈbɑ:skɪtri/|(n)|nghề đan rổ"],
            examplesFinal: ["ask|/ɑ:sk/|(v)|hỏi", "desk|/desk/|(n)|bàn", "task|/tɑ:sk/|(n)|nhiệm vụ", "mask|/mɑ:sk/|(n)|mặt nạ", "risk|/rɪsk/|(n)|rủi ro", "flask|/flɑ:sk/|(n)|bình giữ nhiệt", "tusk|/tʌsk/|(n)|ngà voi", "dusk|/dʌsk/|(n)|chạng vạng", "brisk|/brɪsk/|(adj)|nhanh nhẹn", "disk|/dɪsk/|(n)|đĩa CD", "whisk|/wɪsk/|(n)|cái đánh trứng", "husk|/hʌsk/|(n)|vỏ trấu", "musk|/mʌsk/|(n)|xạ hương", "bask|/bɑ:sk/|(v)|tắm nắng", "asterisk|/ˈæstərɪsk/|(n)|dấu sao"]
        },
        { id: "nd", phonetic: "nd", type: "Consonant Cluster", voiced: true, 
            examplesInitial: [],
            examplesMedial: ["under|/ˈʌndər/|(prep)|bên dưới", "window|/ˈwɪndəʊ/|(n)|cửa sổ", "understand|/ˌʌndəˈstænd/|(v)|hiểu", "hundred|/ˈhʌndrəd/|(n)|một trăm", "condition|/kənˈdɪʃən/|(n)|điều kiện", "handle|/ˈhændəl/|(v)|xử lý", "wonder|/ˈwʌndər/|(v)|tự hỏi", "candy|/ˈkændi/|(n)|kẹo", "random|/ˈrændəm/|(adj)|ngẫu nhiên", "candle|/ˈkændəl/|(n)|cây nến", "standard|/ˈstændəd/|(n)|tiêu chuẩn", "industry|/ˈɪndəstri/|(n)|ngành công nghiệp", "splendid|/ˈsplendɪd/|(adj)|lộng lẫy", "calendar|/ˈkælɪndər/|(n)|lịch", "sandwich|/ˈsændwɪtʃ/|(n)|bánh mì kẹp"],
            examplesFinal: ["and|/ænd/|(conj)|và", "find|/faɪnd/|(v)|tìm", "hand|/hænd/|(n)|bàn tay", "land|/lænd/|(n)|vùng đất", "sand|/sænd/|(n)|cát", "band|/bænd/|(n)|ban nhạc", "stand|/stænd/|(v)|đứng", "pound|/paʊnd/|(n)|đồng bảng", "sound|/saʊnd/|(n)|âm thanh", "round|/raʊnd/|(adj)|tròn", "ground|/graʊnd/|(n)|mặt đất", "mind|/maɪnd/|(n)|tâm trí", "kind|/kaɪnd/|(adj)|tốt bụng", "wind|/wɪnd/|(n)|gió", "send|/send/|(v)|gửi"]
        },
        { id: "nt", phonetic: "nt", type: "Consonant Cluster", voiced: false, 
            examplesInitial: [],
            examplesMedial: ["center|/ˈsentər/|(n)|trung tâm", "winter|/ˈwɪntər/|(n)|mùa đông", "internet|/ˈɪntənet/|(n)|mạng internet", "international|/ˌɪntəˈnæʃənəl/|(adj)|quốc tế", "enter|/ˈentər/|(v)|bước vào", "interview|/ˈɪntəvju:/|(n)|phỏng vấn", "counter|/ˈkaʊntər/|(n)|quầy hàng", "painting|/ˈpeɪntɪŋ/|(n)|bức tranh", "pointing|/ˈpɔɪntɪŋ/|(v)|đang chỉ", "country|/ˈkʌntri/|(n)|quốc gia", "sentence|/ˈsentəns/|(n)|câu", "mental|/ˈmentəl/|(adj)|thuộc tâm thần", "gentle|/ˈdʒentəl/|(adj)|nhẹ nhàng", "rental|/ˈrentəl/|(n)|việc thuê", "dental|/ˈdentəl/|(adj)|thuộc nha khoa"],
            examplesFinal: ["want|/wɒnt/|(v)|muốn", "point|/pɔɪnt/|(n)|điểm", "front|/frʌnt/|(n)|phía trước", "plant|/plɑ:nt/|(n)|thực vật", "ant|/ænt/|(n)|con kiến", "tent|/tent/|(n)|cái lều", "rent|/rent/|(v)|thuê", "sent|/sent/|(v)|đã gửi", "went|/went/|(v)|đã đi", "hunt|/hʌnt/|(v)|săn bắn", "paint|/peɪnt/|(v)|sơn", "print|/prɪnt/|(v)|in ấn", "count|/kaʊnt/|(v)|đếm", "meant|/ment/|(v)|đã ngụ ý", "spent|/spent/|(v)|đã tiêu"]
        },
        { id: "nk", phonetic: "nk", type: "Consonant Cluster", voiced: false, 
            examplesInitial: [],
            examplesMedial: ["monkey|/ˈmʌŋki/|(n)|con khỉ", "donkey|/ˈdɒŋki/|(n)|con lừa", "thinking|/ˈθɪŋkɪŋ/|(n)|suy nghĩ", "drinking|/ˈdrɪŋkɪŋ/|(v)|đang uống", "blanket|/ˈblæŋkɪt/|(n)|cái chăn", "ankle|/ˈæŋkəl/|(n)|mắt cá chân", "uncle|/ˈʌŋkəl/|(n)|chú, bác", "wrinkle|/ˈrɪŋkəl/|(n)|nếp nhăn", "twinkle|/ˈtwɪŋkəl/|(v)|lấp lánh", "sprinkle|/ˈsprɪŋkəl/|(v)|rắc", "crinkle|/ˈkrɪŋkəl/|(v)|làm nhăn", "tinkle|/ˈtɪŋkəl/|(v)|kêu leng keng", "tinker|/ˈtɪŋkər/|(v)|sửa chữa vặt", "bunker|/ˈbʌŋkər/|(n)|hầm trú ẩn", "clinker|/ˈklɪŋkər/|(n)|xỉ than"],
            examplesFinal: ["think|/θɪŋk/|(v)|nghĩ", "drink|/drɪŋk/|(v)|uống", "bank|/bæŋk/|(n)|ngân hàng", "thank|/θæŋk/|(v)|cảm ơn", "pink|/pɪŋk/|(adj)|màu hồng", "sink|/sɪŋk/|(v)|chìm", "link|/lɪŋk/|(n)|liên kết", "rank|/ræŋk/|(n)|xếp hạng", "tank|/tæŋk/|(n)|xe tăng", "blank|/blæŋk/|(adj)|trống không", "chunk|/tʃʌŋk/|(n)|khúc, tảng", "drunk|/drʌŋk/|(adj)|say xỉn", "junk|/dʒʌŋk/|(n)|đồ bỏ đi", "trunk|/trʌŋk/|(n)|cốp xe", "wink|/wɪŋk/|(v)|nháy mắt"]
        },
        { id: "mp", phonetic: "mp", type: "Consonant Cluster", voiced: false, 
            examplesInitial: [],
            examplesMedial: ["simple|/ˈsɪmpəl/|(adj)|đơn giản", "important|/ɪmˈpɔ:tənt/|(adj)|quan trọng", "example|/ɪgˈzɑ:mpəl/|(n)|ví dụ", "completely|/kəmˈpli:tli/|(adv)|hoàn toàn", "company|/ˈkʌmpəni/|(n)|công ty", "computer|/kəmˈpju:tər/|(n)|máy tính", "empty|/ˈempti/|(adj)|trống rỗng", "temperature|/ˈtemprətʃər/|(n)|nhiệt độ", "sympathetic|/ˌsɪmpəˈθetɪk/|(adj)|thông cảm", "champion|/ˈtʃæmpiən/|(n)|nhà vô địch", "complain|/kəmˈpleɪn/|(v)|phàn nàn", "compare|/kəmˈpeə/|(v)|so sánh", "campaign|/kæmˈpeɪn/|(n)|chiến dịch", "campus|/ˈkæmpəs/|(n)|khuôn viên", "bumper|/ˈbʌmpər/|(n)|cản xe"],
            examplesFinal: ["jump|/dʒʌmp/|(v)|nhảy", "camp|/kæmp/|(n)|cắm trại", "lamp|/læmp/|(n)|cái đèn", "bump|/bʌmp/|(v)|va chạm", "pump|/pʌmp/|(n)|cái bơm", "dump|/dʌmp/|(v)|vứt bỏ", "lump|/lʌmp/|(n)|cục, tảng", "stamp|/stæmp/|(n)|con tem", "chimp|/tʃɪmp/|(n)|tinh tinh", "shrimp|/ʃrɪmp/|(n)|con tôm", "cramp|/kræmp/|(n)|chuột rút", "swamp|/swɒmp/|(n)|đầm lầy", "plump|/plʌmp/|(adj)|bụ bẫm", "stump|/stʌmp/|(n)|gốc cây", "ramp|/ræmp/|(n)|đoạn dốc"]
        }
    ]
};
